// AUTO-GENERATED by scripts/generate-departments.mjs — DO NOT EDIT
// Run: npm run generate-departments

import type { GeneratedDepartment } from "./department-types";

export const marinesGeneratedDepartments: GeneratedDepartment[] = [
  {
    "id": "Cargo",
    "name": "Carga",
    "description": "Completa recompensas, gana Spessos y encarga suministros útiles para la tripulación.",
    "color": "#A46106",
    "jobs": [
      {
        "id": "CargoTechnician",
        "name": "Técnico de carga"
      },
      {
        "id": "Quartermaster",
        "name": "Intendente"
      },
      {
        "id": "SalvageSpecialist",
        "name": "Especialista en salvamento"
      }
    ]
  },
  {
    "id": "Civilian",
    "name": "Civiles",
    "description": "Realiza pequeñas tareas útiles para mantener la estación cuerda y bien atendida.",
    "color": "#9FED58",
    "jobs": [
      {
        "id": "Bartender",
        "name": "Camarero"
      },
      {
        "id": "Botanist",
        "name": "Botánico"
      },
      {
        "id": "Boxer",
        "name": "Boxeador"
      },
      {
        "id": "Chaplain",
        "name": "Capellán"
      },
      {
        "id": "Chef",
        "name": "Chef"
      },
      {
        "id": "Clown",
        "name": "Payaso"
      },
      {
        "id": "HeadOfPersonnel",
        "name": "Jefe de personal"
      },
      {
        "id": "Janitor",
        "name": "Conserje"
      },
      {
        "id": "Lawyer",
        "name": "Abogado"
      },
      {
        "id": "Librarian",
        "name": "Bibliotecario"
      },
      {
        "id": "Mime",
        "name": "Mimo"
      },
      {
        "id": "Musician",
        "name": "Músico"
      },
      {
        "id": "Passenger",
        "name": "Pasajero"
      },
      {
        "id": "Reporter",
        "name": "Reportero"
      },
      {
        "id": "Visitor",
        "name": "Visitante"
      },
      {
        "id": "Zookeeper",
        "name": "Cuidador del zoológico"
      },
      {
        "id": "ServiceWorker",
        "name": "Trabajador de servicio"
      }
    ]
  },
  {
    "id": "CentralCommand",
    "name": "Mando Central",
    "description": "Gestiona a la tripulación y haz que trabaje con eficacia.",
    "color": "#0c344d",
    "jobs": [
      {
        "id": "CentralCommandOfficial",
        "name": "Funcionario del Mando Central"
      },
      {
        "id": "CBURN",
        "name": "Oficial de cuarentena del Mando Central"
      },
      {
        "id": "ERTLeader",
        "name": "Líder de ERT"
      },
      {
        "id": "ERTChaplain",
        "name": "Capellán de ERT"
      },
      {
        "id": "ERTJanitor",
        "name": "Conserje de ERT"
      },
      {
        "id": "ERTMedical",
        "name": "Médico de ERT"
      },
      {
        "id": "ERTSecurity",
        "name": "Seguridad de ERT"
      },
      {
        "id": "ERTEngineer",
        "name": "Ingeniero de ERT"
      },
      {
        "id": "DeathSquad",
        "name": "Agente del Mando Central"
      }
    ]
  },
  {
    "id": "Command",
    "name": "Mando",
    "description": "Gestiona a la tripulación y haz que trabaje con eficacia.",
    "color": "#334E6D",
    "jobs": [
      {
        "id": "Captain",
        "name": "Capitán"
      },
      {
        "id": "ChiefEngineer",
        "name": "Ingeniero jefe"
      },
      {
        "id": "ChiefMedicalOfficer",
        "name": "Jefe médico"
      },
      {
        "id": "HeadOfPersonnel",
        "name": "Jefe de personal"
      },
      {
        "id": "HeadOfSecurity",
        "name": "Jefe de seguridad"
      },
      {
        "id": "ResearchDirector",
        "name": "Director de investigación"
      },
      {
        "id": "Quartermaster",
        "name": "Intendente"
      },
      {
        "id": "CentralCommandOfficial",
        "name": "Funcionario del Mando Central"
      },
      {
        "id": "CBURN",
        "name": "Oficial de cuarentena del Mando Central"
      },
      {
        "id": "ERTLeader",
        "name": "Líder de ERT"
      },
      {
        "id": "ERTChaplain",
        "name": "Capellán de ERT"
      },
      {
        "id": "ERTJanitor",
        "name": "Conserje de ERT"
      },
      {
        "id": "ERTMedical",
        "name": "Médico de ERT"
      },
      {
        "id": "ERTSecurity",
        "name": "Seguridad de ERT"
      },
      {
        "id": "ERTEngineer",
        "name": "Ingeniero de ERT"
      },
      {
        "id": "DeathSquad",
        "name": "Agente del Mando Central"
      }
    ]
  },
  {
    "id": "Engineering",
    "name": "Ingeniería",
    "description": "Mantén la energía y la estación en funcionamiento.",
    "color": "#EFB341",
    "jobs": [
      {
        "id": "AtmosphericTechnician",
        "name": "Técnico atmosférico"
      },
      {
        "id": "ChiefEngineer",
        "name": "Ingeniero jefe"
      },
      {
        "id": "StationEngineer",
        "name": "Ingeniero de estación"
      },
      {
        "id": "TechnicalAssistant",
        "name": "Ayudante técnico"
      }
    ]
  },
  {
    "id": "Medical",
    "name": "Medicina",
    "description": "Mantén sana a la tripulación.",
    "color": "#52B4E9",
    "jobs": [
      {
        "id": "Chemist",
        "name": "Químico"
      },
      {
        "id": "ChiefMedicalOfficer",
        "name": "Jefe médico"
      },
      {
        "id": "MedicalDoctor",
        "name": "Médico"
      },
      {
        "id": "MedicalIntern",
        "name": "Médico en prácticas"
      },
      {
        "id": "Psychologist",
        "name": "Psicólogo"
      },
      {
        "id": "Paramedic",
        "name": "Paramédico"
      }
    ]
  },
  {
    "id": "Security",
    "name": "Seguridad",
    "description": "Mantén la paz en la estación.",
    "color": "#DE3A3A",
    "jobs": [
      {
        "id": "HeadOfSecurity",
        "name": "Jefe de seguridad"
      },
      {
        "id": "SecurityCadet",
        "name": "Cadete de seguridad"
      },
      {
        "id": "SecurityOfficer",
        "name": "Oficial de seguridad"
      },
      {
        "id": "Detective",
        "name": "Detective"
      },
      {
        "id": "Warden",
        "name": "Alcaide"
      }
    ]
  },
  {
    "id": "Science",
    "name": "Ciencia",
    "description": "Investiga artefactos y anomalías para inventar equipo nuevo para la estación.",
    "color": "#D381C9",
    "jobs": [
      {
        "id": "ResearchDirector",
        "name": "Director de investigación"
      },
      {
        "id": "Scientist",
        "name": "Científico"
      },
      {
        "id": "ResearchAssistant",
        "name": "Ayudante de investigación"
      }
    ]
  },
  {
    "id": "Silicon",
    "name": "Silicios",
    "description": "Obedece tus leyes y sirve a la tripulación.",
    "color": "#D381C9",
    "jobs": [
      {
        "id": "Borg",
        "name": "Cíborg"
      },
      {
        "id": "StationAi",
        "name": "IA de la estación"
      }
    ]
  },
  {
    "id": "Specific",
    "name": "Específicos de la estación",
    "description": "Puestos que no existen en todas las estaciones.",
    "color": "#9FED58",
    "jobs": [
      {
        "id": "Boxer",
        "name": "Boxeador"
      },
      {
        "id": "Reporter",
        "name": "Reportero"
      },
      {
        "id": "Zookeeper",
        "name": "Cuidador del zoológico"
      },
      {
        "id": "Psychologist",
        "name": "Psicólogo"
      }
    ]
  },
  {
    "id": "CMDepartmentBase",
    "name": "CM Department Base",
    "description": "",
    "color": "#888888",
    "jobs": []
  },
  {
    "id": "CMCommand",
    "name": "Mando",
    "description": "El Departamento de Mando es el cerebro de la UNS Almayer: dirige y coordina a los escuadrones y al resto del personal de apoyo de la nave para combatir y vencer a los alienígenas.",
    "color": "#334E6D",
    "jobs": [
      {
        "id": "CMCommandingOfficer",
        "name": "Oficial al mando"
      },
      {
        "id": "CMExecutiveOfficer",
        "name": "Oficial ejecutivo"
      },
      {
        "id": "CMStaffOfficer",
        "name": "Oficial de Estado Mayor"
      },
      {
        "id": "CMPVEPlatoonCommander",
        "name": "Comandante de pelotón"
      },
      {
        "id": "CMRoyalMarinesTroopCommanderPVE",
        "name": "Comandante"
      }
    ]
  },
  {
    "id": "CMEngineering",
    "name": "Ingeniería",
    "description": "Tu trabajo consiste en mantener el motor de la nave y asegurar que todo siga funcionando.",
    "color": "#A66300",
    "jobs": [
      {
        "id": "CMChiefEngineer",
        "name": "Ingeniero jefe"
      },
      {
        "id": "CMOrdnanceTech",
        "name": "Técnico de armamento"
      },
      {
        "id": "CMMaintTech",
        "name": "Técnico de mantenimiento"
      }
    ]
  },
  {
    "id": "CMSquad",
    "name": "Marines",
    "description": "Constituyen la principal fuerza de combate de la Almayer y son enviados a la superficie para enfrentarse a toda clase de peligros por el sector Zypheron.",
    "color": "#DE3A3A",
    "jobs": [
      {
        "id": "CMRifleman",
        "name": "Fusilero"
      },
      {
        "id": "CMSquadLeader",
        "name": "Líder de sección"
      },
      {
        "id": "CMFireteamLeader",
        "name": "Líder de escuadra"
      },
      {
        "id": "CMWeaponsSpecialist",
        "name": "Especialista en armamento"
      },
      {
        "id": "CMSmartGunOperator",
        "name": "Operador de smartgun"
      },
      {
        "id": "CMHospitalCorpsman",
        "name": "Sanitario de combate"
      },
      {
        "id": "CMCombatTech",
        "name": "Técnico de combate"
      },
      {
        "id": "CMPVERifleman",
        "name": "CMPVE Rifleman"
      },
      {
        "id": "CMPVEHospitalCorpsman",
        "name": "Sanitario de combate"
      },
      {
        "id": "CMPVESquadLeader",
        "name": "Líder de sección"
      },
      {
        "id": "CMPVESmartGunOperator",
        "name": "Operador de smartgun"
      },
      {
        "id": "CMPVESectionSergeant",
        "name": "Sargento de sección"
      },
      {
        "id": "CMRoyalMarinesTroopSargePVE",
        "name": "Sargento"
      },
      {
        "id": "CMRoyalMarinesSectionLeaderPVE",
        "name": "Líder de sección"
      },
      {
        "id": "CMRoyalMarinesTeamLeaderPVE",
        "name": "Líder de equipo"
      },
      {
        "id": "CMRoyalMarinesAssaultEngineerPVE",
        "name": "Ingeniero de asalto"
      },
      {
        "id": "CMRoyalMarinesSmartgunnerPVE",
        "name": "Artillero de GPMG"
      },
      {
        "id": "CMRoyalMarinesBombSpecPVE",
        "name": "Especialista en bombardeo"
      },
      {
        "id": "CMRoyalMarinesScoutSniperPVE",
        "name": "Francotirador explorador"
      },
      {
        "id": "CMRoyalMarinesMedicPVE",
        "name": "Auxiliar médico"
      },
      {
        "id": "CMRoyalMarinesRiflemanPVE",
        "name": "Fusilero"
      }
    ]
  },
  {
    "id": "CMMedbay",
    "name": "Enfermería",
    "description": "Atiende a todos los pacientes que lleguen a la enfermería. Traslada a los marines heridos desde el hangar hasta allí.",
    "color": "#008160",
    "jobs": [
      {
        "id": "CMCMO",
        "name": "Oficial médico jefe"
      },
      {
        "id": "CMDoctor",
        "name": "Médico"
      },
      {
        "id": "CMResearcher",
        "name": "Investigador"
      },
      {
        "id": "CMNurse",
        "name": "Enfermero"
      },
      {
        "id": "RMCFieldDoctor",
        "name": "Médico de campaña"
      }
    ]
  },
  {
    "id": "CMMilitaryPolice",
    "name": "Policía Militar",
    "description": "Haz cumplir la Ley Militar de los Marines. Detén a los criminales. Mantén a salvo al personal de la nave.",
    "color": "#DE3A3A",
    "jobs": [
      {
        "id": "CMChiefMP",
        "name": "Jefe de la Policía Militar"
      },
      {
        "id": "CMMilitaryWarden",
        "name": "Alcaide militar"
      },
      {
        "id": "CMMilitaryPolice",
        "name": "Policía militar"
      }
    ]
  },
  {
    "id": "CMOther",
    "name": "Otros",
    "description": "\"\"",
    "color": "#595959",
    "jobs": [
      {
        "id": "RMCJobSynthetic",
        "name": "Sintético de la UNMC"
      },
      {
        "id": "CMLiaison",
        "name": "Enlace corporativo"
      },
      {
        "id": "CMCorrespondent",
        "name": "Corresponsal"
      },
      {
        "id": "CMMessTech",
        "name": "Técnico de comedor"
      }
    ]
  },
  {
    "id": "CMRequisitions",
    "name": "Requisiciones",
    "description": "Suministra equipo a los marines.",
    "color": "#5F4519",
    "jobs": [
      {
        "id": "CMQuartermaster",
        "name": "Oficial de logística"
      },
      {
        "id": "CMCargoTech",
        "name": "Técnico de requisiciones"
      }
    ]
  },
  {
    "id": "CMAuxiliarySupport",
    "name": "Apoyo auxiliar",
    "description": "El personal de apoyo auxiliar ayuda a los marines mediante potencia de fuego u otros medios.",
    "color": "#C38312",
    "jobs": [
      {
        "id": "CMAuxiliarySupportOfficer",
        "name": "Oficial de apoyo auxiliar"
      },
      {
        "id": "CMPilotDropship",
        "name": "Piloto de nave de descenso"
      },
      {
        "id": "CMPilotGunship",
        "name": "Oficial de pilotaje"
      },
      {
        "id": "CMDropshipCrewChief",
        "name": "Jefe de tripulación de nave de descenso"
      },
      {
        "id": "CMIntelOfficer",
        "name": "Oficial de inteligencia"
      },
      {
        "id": "CMSeniorEnlistedAdvisor",
        "name": "Asesor superior de tropa"
      }
    ]
  },
  {
    "id": "CMSurvivor",
    "name": "Superviviente",
    "description": "Sobrevive siempre que puedas, por tu cuenta o junto a otros supervivientes.",
    "color": "#C38312",
    "jobs": [
      {
        "id": "RMCJobSyntheticColony",
        "name": "Sintético colonial"
      },
      {
        "id": "CMSurvivor",
        "name": "Colono civil"
      },
      {
        "id": "CMSurvivorDoctor",
        "name": "Colono médico"
      },
      {
        "id": "CMSurvivorEngineer",
        "name": "Colono ingeniero"
      },
      {
        "id": "CMSurvivorSecurity",
        "name": "Colono de seguridad"
      },
      {
        "id": "CMSurvivorScientist",
        "name": "Colono científico"
      },
      {
        "id": "CMSurvivorCorporate",
        "name": "Colono corporativo"
      },
      {
        "id": "RMCSurvivorCommandingOfficer",
        "name": "Comandante superviviente"
      },
      {
        "id": "RMCSurvivorMilitary",
        "name": "Superviviente militar"
      }
    ]
  },
  {
    "id": "CMUDepartmentProvost",
    "name": "Policía militar del Provost",
    "description": "Haz cumplir la Ley Militar y los SOP. Detén a los delincuentes.",
    "color": "#DE3A3A",
    "jobs": [
      {
        "id": "CMUJobINDFORProvostAdvisor",
        "name": "Asesor del Provost"
      },
      {
        "id": "CMUJobINDFORProvostInspector",
        "name": "Inspector del Provost"
      },
      {
        "id": "CMUJobINDFORProvostInspectorChief",
        "name": "Inspector jefe del Provost"
      },
      {
        "id": "CMUJobINDFORProvostEnforcer",
        "name": "Agente ejecutor"
      },
      {
        "id": "CMUJobINDFORProvostEnforcerMedic",
        "name": "Agente sanitario"
      },
      {
        "id": "CMUJobINDFORProvostMarshal",
        "name": "Mariscal del Provost"
      },
      {
        "id": "CMUJobINDFORProvostMarshalDeputy",
        "name": "Mariscal adjunto del Provost"
      },
      {
        "id": "CMUJobINDFORProvostSpcAgent",
        "name": "Agente especial"
      },
      {
        "id": "CMUJobINDFORProvostSpcComms",
        "name": "Especialista en comunicaciones"
      },
      {
        "id": "CMUJobINDFORProvostSpcMedic",
        "name": "Especialista médico"
      },
      {
        "id": "CMUJobINDFORProvostTeamLeader",
        "name": "Jefe de equipo"
      }
    ]
  },
  {
    "id": "AU14DepartmentAmbassadors",
    "name": "Embajador",
    "description": "Embajadores de distintos países.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianAmbassadorUPP",
        "name": "Embajador de la UPP"
      },
      {
        "id": "AU14JobCivilianAmbassadorUA",
        "name": "Embajador de la UA"
      },
      {
        "id": "AU14JobCivilianAmbassadorTWE",
        "name": "Embajador de la TWE"
      },
      {
        "id": "AU14JobCivilianAmbassadorICSC",
        "name": "Embajador de la ICSC"
      },
      {
        "id": "AU14JobCivilianAmbassadorCCA",
        "name": "Embajador de la CCA"
      }
    ]
  },
  {
    "id": "AU14DepartmentCivilian",
    "name": "Colono",
    "description": "Colonos en general.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianJournalist",
        "name": "Periodista"
      },
      {
        "id": "AU14JobCivilianUSASFRecruiter",
        "name": "Reclutador de la UA"
      },
      {
        "id": "AU14JobCivilianColonySynthetic",
        "name": "Sintético de operaciones coloniales"
      }
    ]
  },
  {
    "id": "AU14DepartmentColonialLiberationFront",
    "name": "Insurgencia",
    "description": "Para algunos, la Insurgencia es la milicia que mantiene la paz; para otros, son rebeldes que se oponen al gobierno. Como miembro de la insurgencia, luchas por la libertad contra los numerosos gobiernos del Sector Neroid, que creen neciamente que vuestros hogares les pertenecen.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCLFGuerilla",
        "name": "Guerrillero de la CLF"
      },
      {
        "id": "AU14JobCLFSapper",
        "name": "Zapador de la CLF"
      },
      {
        "id": "AU14JobCLFCellLeader",
        "name": "Líder de célula de la CLF"
      },
      {
        "id": "AU14JobCLFRadioOperator",
        "name": "Operador de radio de la CLF"
      },
      {
        "id": "AU14JobCLFPhysician",
        "name": "Médico de la CLF"
      },
      {
        "id": "AU14JobCLFSurgeon",
        "name": "Cirujano de la CLF"
      }
    ]
  },
  {
    "id": "AU14DepartmentColonyCommand",
    "name": "Mando colonial",
    "description": "Supervisa todas las operaciones y el gobierno de la colonia.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianColonyAdministrator",
        "name": "Administrador de la colonia"
      },
      {
        "id": "AU14JobCivilianColonyAdminAssistant",
        "name": "Administrador adjunto"
      },
      {
        "id": "AU14JobCivilianHeadOfService",
        "name": "Jefe de servicios"
      },
      {
        "id": "AU14JobCivilianHeadOfEngineering",
        "name": "Jefe de ingeniería"
      },
      {
        "id": "AU14JobLEOLeaderBase",
        "name": "Jefe de las fuerzas del orden"
      }
    ]
  },
  {
    "id": "AU14DepartmentColonyMedical",
    "name": "Medicina colonial",
    "description": "Responsable de la atención sanitaria y el tratamiento de urgencia.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianHeadPhysician",
        "name": "Médico jefe"
      },
      {
        "id": "AU14JobCivilianPhysician",
        "name": "Médico"
      },
      {
        "id": "AU14JobCivilianNurse",
        "name": "Enfermero"
      },
      {
        "id": "AU14JobCivilianEthicsAndWellnessAdvisor",
        "name": "Asesor de ética y bienestar"
      },
      {
        "id": "AU14JobCivilianEmergencyResponseOfficer",
        "name": "Oficial de respuesta a emergencias"
      }
    ]
  },
  {
    "id": "AU14DepartmentColonySecurity",
    "name": "Seguridad y fuerzas del orden coloniales",
    "description": "Hace cumplir la ley, realiza detenciones, protege al personal y mantiene el orden.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobLEOLeaderBase",
        "name": "Jefe de las fuerzas del orden"
      },
      {
        "id": "AU14JobLEOBase",
        "name": "Agente de las fuerzas del orden"
      },
      {
        "id": "AU14JobCivilianCWPSRanger",
        "name": "Guardabosques de la CWPS"
      },
      {
        "id": "AU14JobCivilianPaPOfficer",
        "name": "Oficial de la PAP"
      },
      {
        "id": "AU14JobCivilianCMBMarshal",
        "name": "Mariscal de la CMB"
      },
      {
        "id": "AU14JobCivilianCMBDeputy",
        "name": "Ayudante de la CMB"
      },
      {
        "id": "AU14JobCivilianNSPAConstable",
        "name": "Agente de la NSPA"
      },
      {
        "id": "AU14JobCivilianNSPAInspector",
        "name": "Inspector de la NSPA"
      },
      {
        "id": "AU14JobCivilianColonySecurityLeader",
        "name": "Jefe de seguridad colonial"
      },
      {
        "id": "AU14JobCivilianColonySecurityOfficer",
        "name": "Oficial de seguridad colonial"
      }
    ]
  },
  {
    "id": "AU14DepartmentCorporate",
    "name": "Empleados corporativos",
    "description": "Colonos contratados directamente por Weyland-Yutani Corporation para puestos directivos o de seguridad.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianCorporateAdministrator",
        "name": "Administrador corporativo"
      },
      {
        "id": "AU14JobCivilianCorporateAdminAssistant",
        "name": "Asistente de administración corporativa"
      },
      {
        "id": "AU14JobCivilianCorporateLiaison",
        "name": "Enlace"
      },
      {
        "id": "AU14JobWYGuard",
        "name": "Agente de seguridad"
      },
      {
        "id": "AU14JobCivilianScientist",
        "name": "Científico"
      },
      {
        "id": "AU14JobCivilianKellandWarden",
        "name": "Alcaide de Kelland"
      },
      {
        "id": "AU14JobCivilianCorporateAssistant",
        "name": "Asistente corporativo"
      },
      {
        "id": "AU14JobColonyWorkingJoe",
        "name": "AU14Job Colony Working Joe"
      }
    ]
  },
  {
    "id": "AU14DepartmentCriminal",
    "name": "Delincuentes de la colonia",
    "description": "Delincuentes y prisioneros de la colonia.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianPrisoner",
        "name": "Prisionero"
      },
      {
        "id": "AU14JobMobGoon",
        "name": "Matón de la mafia"
      },
      {
        "id": "AU14JobMobBoss",
        "name": "Jefe de la mafia"
      }
    ]
  },
  {
    "id": "AU14DepartmentEngineering",
    "name": "Ingeniería y logística colonial",
    "description": "Mantiene la infraestructura y garantiza que los suministros lleguen donde hacen falta.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianHeadOfEngineering",
        "name": "Jefe de ingeniería"
      },
      {
        "id": "AU14JobCivilianEngineer",
        "name": "Ingeniero"
      },
      {
        "id": "AU14JobCivilianFreightSystemsSpecialist",
        "name": "Especialista en sistemas de carga"
      }
    ]
  },
  {
    "id": "AU14DepartmentGovernmentForces",
    "name": "Fuerzas Gubernamentales",
    "description": "Fuerzas Gubernamentales",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobGOVFORPlatCo",
        "name": "AU14Job GOVFOR Plat Co"
      },
      {
        "id": "AU14JobGOVFORAdjutant",
        "name": "AU14Job GOVFOR Adjutant"
      },
      {
        "id": "AU14JobGOVFORPlatOp",
        "name": "AU14Job GOVFOR Plat Op"
      },
      {
        "id": "AU14JobGOVFORadvisor",
        "name": "AU14Job GOVFO Radvisor"
      },
      {
        "id": "AU14JobGOVFOROfficerIntel",
        "name": "AU14Job GOVFOR Officer Intel"
      },
      {
        "id": "AU14JobGOVFORSectionSergeant",
        "name": "AU14Job GOVFOR Section Sergeant"
      },
      {
        "id": "AU14JobGOVFORSquadSergeant",
        "name": "AU14Job GOVFOR Squad Sergeant"
      },
      {
        "id": "AU14JobGOVFORRadioTelephoneOperator",
        "name": "AU14Job GOVFOR Radio Telephone Operator"
      },
      {
        "id": "AU14JobGOVFORRadioTrafficOperator",
        "name": "AU14Job GOVFOR Radio Traffic Operator"
      },
      {
        "id": "AU14JobGOVFORSquadRifleman",
        "name": "AU14Job GOVFOR Squad Rifleman"
      },
      {
        "id": "CMUJobGOVFORDroneOperator",
        "name": "CMU Job GOVFOR Drone Operator"
      },
      {
        "id": "AU14JobGOVFORWeaponsSpecialist",
        "name": "AU14Job GOVFOR Weapons Specialist"
      },
      {
        "id": "AU14JobGOVFORSquadAutomaticRifleman",
        "name": "AU14Job GOVFOR Squad Automatic Rifleman"
      },
      {
        "id": "AU14JobGOVFORSquadCombatTech",
        "name": "AU14Job GOVFOR Squad Combat Tech"
      },
      {
        "id": "AU14JobGOVFOREngineeringTech",
        "name": "AU14Job GOVFOR Engineering Tech"
      },
      {
        "id": "AU14JobGOVFOROfficerLogistics",
        "name": "AU14Job GOVFOR Officer Logistics"
      },
      {
        "id": "AU14JobGOVFORAuxTech",
        "name": "AU14Job GOVFOR Aux Tech"
      },
      {
        "id": "AU14JobGOVFOROfficerMedical",
        "name": "AU14Job GOVFOR Officer Medical"
      },
      {
        "id": "AU14JobGOVFORMilitaryDoctor",
        "name": "AU14Job GOVFOR Military Doctor"
      },
      {
        "id": "AU14JobGOVFORPlatoonCorpsman",
        "name": "AU14Job GOVFOR Platoon Corpsman"
      },
      {
        "id": "AU14JobGOVFORNurse",
        "name": "AU14Job GOVFOR Nurse"
      },
      {
        "id": "AU14JobGOVFOROfficerMP",
        "name": "AU14Job GOVFOR Officer MP"
      },
      {
        "id": "AU14JobGOVFORMilitaryPoliceMan",
        "name": "AU14Job GOVFOR Military Police Man"
      },
      {
        "id": "AU14JobGOVFOROfficerEngi",
        "name": "AU14Job GOVFOR Officer Engi"
      },
      {
        "id": "AU14JobGOVFORVehicleCrewman",
        "name": "AU14Job GOVFOR Vehicle Crewman"
      },
      {
        "id": "AU14JobGOVFORVehicleCommander",
        "name": "AU14Job GOVFOR Vehicle Commander"
      },
      {
        "id": "AU14JobGOVFORDSPilot",
        "name": "AU14Job GOVFORDS Pilot"
      },
      {
        "id": "AU14JobGOVFORDCC",
        "name": "AU14Job GOVFORDCC"
      },
      {
        "id": "AU14JobGOVFORAuxSupportSynth",
        "name": "AU14Job GOVFOR Aux Support Synth"
      },
      {
        "id": "AU14JobGOVFORWorkingJoe",
        "name": "AU14Job GOVFOR Working Joe"
      },
      {
        "id": "AU14JobGOVFORCombatCorrespondent",
        "name": "AU14Job GOVFOR Combat Correspondent"
      }
    ]
  },
  {
    "id": "AU14DepartmentHydroponics",
    "name": "AU14Department Hydroponics",
    "description": "",
    "color": "#888888",
    "jobs": []
  },
  {
    "id": "AU14DepartmentLabor",
    "name": "Mano de obra colonial",
    "description": "Colonos que realizan trabajos como minería y agricultura. Es el departamento más esencial y común de la colonia, y a menudo sirve de trampolín para pasar a otros departamentos.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianForeman",
        "name": "Capataz"
      },
      {
        "id": "AU14JobCivilianColonist",
        "name": "Colono"
      }
    ]
  },
  {
    "id": "AU14DepartmentLumbermill",
    "name": "AU14Department Lumbermill",
    "description": "",
    "color": "#888888",
    "jobs": []
  },
  {
    "id": "AU14DepartmentOpfor",
    "name": "Fuerzas de oposición",
    "description": "Fuerzas de oposición",
    "color": "#9e1a0b",
    "jobs": [
      {
        "id": "AU14JobOPFORPlatCo",
        "name": "AU14Job OPFOR Plat Co"
      },
      {
        "id": "AU14JobOPFORPlatOp",
        "name": "AU14Job OPFOR Plat Op"
      },
      {
        "id": "AU14JobOPFORadvisor",
        "name": "AU14Job OPFO Radvisor"
      },
      {
        "id": "AU14JobOPFORSectionSergeant",
        "name": "AU14Job OPFOR Section Sergeant"
      },
      {
        "id": "AU14JobOPFORSquadSergeant",
        "name": "AU14Job OPFOR Squad Sergeant"
      },
      {
        "id": "AU14JobOPFORRadioTelephoneOperator",
        "name": "AU14Job OPFOR Radio Telephone Operator"
      },
      {
        "id": "AU14JobOPFORSquadRifleman",
        "name": "AU14Job OPFOR Squad Rifleman"
      },
      {
        "id": "AU14JobOPFORSquadAutomaticRifleman",
        "name": "AU14Job OPFOR Squad Automatic Rifleman"
      },
      {
        "id": "AU14JobOPFORSquadCombatTech",
        "name": "AU14Job OPFOR Squad Combat Tech"
      },
      {
        "id": "AU14JobOPFORVehicleCrewman",
        "name": "AU14Job OPFOR Vehicle Crewman"
      },
      {
        "id": "AU14JobOPFORPlatoonCorpsman",
        "name": "AU14Job OPFOR Platoon Corpsman"
      },
      {
        "id": "AU14JobOPFORAuxTech",
        "name": "AU14Job OPFOR Aux Tech"
      },
      {
        "id": "AU14JobOPFORDSPilot",
        "name": "AU14Job OPFORDS Pilot"
      },
      {
        "id": "AU14JobOPFORDCC",
        "name": "AU14Job OPFORDCC"
      },
      {
        "id": "AU14JobOPFORAuxSupportSynth",
        "name": "AU14Job OPFOR Aux Support Synth"
      },
      {
        "id": "AU14JobOPFORWorkingJoe",
        "name": "AU14Job OPFOR Working Joe"
      },
      {
        "id": "AU14JobOPFORMilitaryDoctor",
        "name": "AU14Job OPFOR Military Doctor"
      },
      {
        "id": "AU14JobOPFORMilitaryPoliceMan",
        "name": "AU14Job OPFOR Military Police Man"
      }
    ]
  },
  {
    "id": "AU14DepartmentOrbital",
    "name": "Estación orbital",
    "description": "Opera la estación orbital: gestiona el comercio y el salvamento, se ocupa de la carga y el atraque, hace cumplir la normativa y administra justicia.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianOrbitalArbiter",
        "name": "Árbitro orbital"
      },
      {
        "id": "AU14JobCivilianOrbitalLawyer",
        "name": "Consejero jurídico orbital"
      }
    ]
  },
  {
    "id": "AU14DepartmentServices",
    "name": "Servicios",
    "description": "Colonos que prestan servicios a la colonia, como alimentación, gestión de residuos y comercio.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobCivilianHeadOfService",
        "name": "Jefe de servicios"
      },
      {
        "id": "AU14JobCivilianFoodServiceWorker",
        "name": "Trabajador de alimentación"
      },
      {
        "id": "AU14JobCivilianShopkeep",
        "name": "Tendero"
      },
      {
        "id": "AU14JobCivilianWasteManagementSpecialist",
        "name": "Especialista en gestión de residuos"
      }
    ]
  },
  {
    "id": "AU14DepartmentThirdParty",
    "name": "Tercer bando",
    "description": "Selecciona este puesto para jugar como miembro de un tercer bando.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobThirdPartyLeader",
        "name": "Líder de tercera facción"
      },
      {
        "id": "AU14JobThirdPartyMember",
        "name": "Miembro de tercera facción"
      }
    ]
  },
  {
    "id": "AU14DepartmentThreat",
    "name": "Miembro de amenaza",
    "description": "Selecciona este puesto para jugar como la amenaza.",
    "color": "#e3ce94",
    "jobs": [
      {
        "id": "AU14JobThreatLeader",
        "name": "Líder de amenaza"
      },
      {
        "id": "AU14JobThreatMember",
        "name": "Miembro de amenaza"
      }
    ]
  }
];
