// AUTO-GENERATED by scripts/generate-guides.mjs — DO NOT EDIT
// Lightweight lookup maps for client components (no guide content)
// Run: npm run generate-guides

import type { GuideMeta } from "./guide-types";

export const marinesGuideIdToSlug: Record<string, string> = {
  "NewPlayer": "new-player",
  "Controls": "controls",
  "Radio": "radio",
  "CharacterCreation": "character-creation",
  "YourFirstCharacter": "your-first-character",
  "Species": "species",
  "Arachnid": "arachnid",
  "Diona": "diona",
  "Dwarf": "dwarf",
  "Human": "human",
  "Moth": "moth",
  "Reptilian": "reptilian",
  "SlimePerson": "slime-person",
  "Vox": "vox",
  "SS14": "ss14",
  "Jobs": "jobs",
  "Service": "service",
  "Bartender": "bartender",
  "Botany": "botany",
  "Chef": "chef",
  "Janitorial": "janitorial",
  "Cargo": "cargo",
  "CargoBounties": "cargo-bounties",
  "Salvage": "salvage",
  "Medical": "medical",
  "MedicalDoctor": "medical-doctor",
  "Chemist": "chemist",
  "Botanicals": "botanicals",
  "AdvancedBrute": "advanced-brute",
  "Cloning": "cloning",
  "Cryogenics": "cryogenics",
  "Science": "science",
  "Technologies": "technologies",
  "AnomalousResearch": "anomalous-research",
  "APE": "ape",
  "ScannersAndVessels": "scanners-and-vessels",
  "Xenoarchaeology": "xenoarchaeology",
  "ArtifactReports": "artifact-reports",
  "Robotics": "robotics",
  "Cyborgs": "cyborgs",
  "Engineering": "engineering",
  "Construction": "construction",
  "Airlocks": "airlocks",
  "AirlockSecurity": "airlock-security",
  "ExpandingRepairingStation": "expanding-repairing-station",
  "WirePanels": "wire-panels",
  "Power": "power",
  "Generators": "generators",
  "PortableGenerator": "portable-generator",
  "AME": "ame",
  "SingularityTeslaEngine": "singularity-tesla-engine",
  "SingularityEngine": "singularity-engine",
  "TeslaEngine": "tesla-engine",
  "TEG": "teg",
  "RTG": "rtg",
  "SolarPanels": "solar-panels",
  "InspectingPower": "inspecting-power",
  "PowerStorage": "power-storage",
  "Ramping": "ramping",
  "VoltageNetworks": "voltage-networks",
  "Atmospherics": "atmospherics",
  "GasManipulation": "gas-manipulation",
  "AtmosphereInOut": "atmosphere-in-out",
  "AirVent": "air-vent",
  "PassiveVent": "passive-vent",
  "AirInjector": "air-injector",
  "AirScrubber": "air-scrubber",
  "PortableScrubber": "portable-scrubber",
  "Pipes": "pipes",
  "Pumps": "pumps",
  "Valves": "valves",
  "ManualValve": "manual-valve",
  "SignalValve": "signal-valve",
  "PneumaticValve": "pneumatic-valve",
  "PassiveGate": "passive-gate",
  "PressureRegulator": "pressure-regulator",
  "MixingAndFiltering": "mixing-and-filtering",
  "GasCanisters": "gas-canisters",
  "Thermomachines": "thermomachines",
  "Radiators": "radiators",
  "GasCondensing": "gas-condensing",
  "AtmosphericsSystems": "atmospherics-systems",
  "PipeNetworks": "pipe-networks",
  "DeviceMonitoringAndControl": "device-monitoring-and-control",
  "AirAlarms": "air-alarms",
  "AtmosphericAlertsComputer": "atmospheric-alerts-computer",
  "AtmosphericNetworkMonitor": "atmospheric-network-monitor",
  "FireAndGasControl": "fire-and-gas-control",
  "GasMiningAndStorage": "gas-mining-and-storage",
  "AtmosphericUpsets": "atmospheric-upsets",
  "Fires": "fires",
  "Spacing": "spacing",
  "AtmosTools": "atmos-tools",
  "Gasses": "gasses",
  "ShuttleCraft": "shuttle-craft",
  "Networking": "networking",
  "AccessConfigurator": "access-configurator",
  "Security": "security",
  "Forensics": "forensics",
  "Defusal": "defusal",
  "CriminalRecords": "criminal-records",
  "SpaceLaw": "space-law",
  "SpaceLawCrimeList": "space-law-crime-list",
  "Command": "command",
  "Survival": "survival",
  "Antagonists": "antagonists",
  "Traitors": "traitors",
  "Thieves": "thieves",
  "Revolutionaries": "revolutionaries",
  "NuclearOperatives": "nuclear-operatives",
  "SpaceNinja": "space-ninja",
  "Wizard": "wizard",
  "Zombies": "zombies",
  "MinorAntagonists": "minor-antagonists",
  "Glossary": "glossary",
  "RMC14": "rmc14",
  "RMCGuideNewPlayer": "rmc-guide-new-player",
  "RMCGuideRoleRifleman": "rmc-guide-role-rifleman",
  "RMCGuideRoleDrone": "rmc-guide-role-drone",
  "RMCGuideMarineRoles": "rmc-guide-marine-roles",
  "RMCSurvivor": "rmc-survivor",
  "RMCMedical": "rmc-medical",
  "AU14MedicalV2": "au14medical-v2",
  "RMCRequisitions": "rmc-requisitions",
  "RMCIntel": "rmc-intel",
  "RMCGuideRoleMilitaryPolice": "rmc-guide-role-military-police",
  "RMCGuideRoleCombatTechnician": "rmc-guide-role-combat-technician",
  "RMCGuideRoleMaintenanceTechnician": "rmc-guide-role-maintenance-technician",
  "RMCGuideRoleSGO": "rmc-guide-role-sgo",
  "RMCGuideCommandRoles": "rmc-guide-command-roles",
  "RMCGuideRoleSpec": "rmc-guide-role-spec",
  "RMCGuideRoleSpecDemo": "rmc-guide-role-spec-demo",
  "RMCGuideRoleSpecGrenadier": "rmc-guide-role-spec-grenadier",
  "RMCGuideRoleSpecScout": "rmc-guide-role-spec-scout",
  "RMCGuideRoleSpecSniper": "rmc-guide-role-spec-sniper",
  "RMCGuideRoleCAS": "rmc-guide-role-cas",
  "RMCGuideMarineCommunications": "rmc-guide-marine-communications",
  "RMCGuideCorporateLiaison": "rmc-guide-corporate-liaison",
  "RMCGuideSquadLeader": "rmc-guide-squad-leader",
  "RMCGuideMarineStructures": "rmc-guide-marine-structures",
  "RMCGuideCommunicationsTowers": "rmc-guide-communications-towers",
  "RMCGuideRoleMortar": "rmc-guide-role-mortar",
  "RMCGuideXenonidRoles": "rmc-guide-xenonid-roles",
  "RMCGuideXenonidT1": "rmc-guide-xenonid-t1",
  "RMCGuideRoleDefender": "rmc-guide-role-defender",
  "RMCGuideRoleSentinel": "rmc-guide-role-sentinel",
  "RMCGuideRoleRunner": "rmc-guide-role-runner",
  "RMCGuideXenonidT2": "rmc-guide-xenonid-t2",
  "RMCGuideRoleWarrior": "rmc-guide-role-warrior",
  "RMCGuideRoleSpitter": "rmc-guide-role-spitter",
  "RMCGuideRoleLurker": "rmc-guide-role-lurker",
  "RMCGuideRoleVampire": "rmc-guide-role-vampire",
  "RMCGuideRoleHivelord": "rmc-guide-role-hivelord",
  "RMCGuideRoleDesigner": "rmc-guide-role-designer",
  "RMCGuideRoleBurrower": "rmc-guide-role-burrower",
  "RMCGuideRoleCarrier": "rmc-guide-role-carrier",
  "RMCGuideRoleEggsac": "rmc-guide-role-eggsac",
  "RMCGuideXenonidT3": "rmc-guide-xenonid-t3",
  "RMCGuideRoleCrusher": "rmc-guide-role-crusher",
  "RMCGuideRolePraetorian": "rmc-guide-role-praetorian",
  "RMCGuideRoleValkyrie": "rmc-guide-role-valkyrie",
  "RMCGuideRoleOppressor": "rmc-guide-role-oppressor",
  "RMCGuideRoleVanguard": "rmc-guide-role-vanguard",
  "RMCGuideRoleRavager": "rmc-guide-role-ravager",
  "RMCGuideRoleBoiler": "rmc-guide-role-boiler",
  "RMCGuideRoleSapper": "rmc-guide-role-sapper",
  "RMCGuideRoleQueen": "rmc-guide-role-queen",
  "RMCGuideRoleParasite": "rmc-guide-role-parasite",
  "RMCGuideXenonidStructures": "rmc-guide-xenonid-structures",
  "RMCGuideHiveStructures": "rmc-guide-hive-structures",
  "RMCGuideResinHoles": "rmc-guide-resin-holes",
  "RMCGuideXenonidMap": "rmc-guide-xenonid-map",
  "RMCGuideFood": "rmc-guide-food",
  "RMCGuideDrinks": "rmc-guide-drinks",
  "CMUResearchIndex": "cmu-research-index",
  "CMUResearch": "cmu-research",
  "CMURDT": "cmurdt",
  "CMUXRF": "cmuxrf",
  "CMUSIM": "cmusim",
  "CMUBotany": "cmu-botany",
  "RMCChemicals": "rmc-chemicals",
  "RMCMedicine": "rmc-medicine",
  "RMCOrdinanceChemicals": "rmc-ordinance-chemicals",
  "RMCOverview": "rmc-overview",
  "AU14RulesZeroTolerance": "au14rules-zero-tolerance",
  "AU14RulesGeneral": "au14rules-general",
  "AU14RulesRoleplay": "au14rules-roleplay",
  "AU14HighRoleplayRoles": "au14high-roleplay-roles",
  "AU14GamemodeRulesOverview": "au14gamemode-rules-overview",
  "AU14GamemodeRulesInsurgency": "au14gamemode-rules-insurgency",
  "AU14SOP": "au14sop",
  "AU14SOPRulesofEngagement": "au14sop-rulesof-engagement",
  "AU14SOPRankStructure": "au14sop-rank-structure",
  "AU14SOPEquipmentAndPersonnel": "au14sop-equipment-and-personnel",
  "AU14SOPCommand": "au14sop-command",
  "AU14SOPDropshipsandAircraft": "au14sop-dropshipsand-aircraft",
  "AU14SOPThirdParty": "au14sop-third-party",
  "AU14SOPDeployment": "au14sop-deployment",
  "AU14SOPVehicles": "au14sop-vehicles",
  "AU14UCMJ": "au14ucmj",
  "AU14UCMJLawRankStructure": "au14ucmj-law-rank-structure",
  "AU14UCMJRightToAppeal": "au14ucmj-right-to-appeal",
  "AU14UCMJNJP": "au14ucmjnjp",
  "AU14UCMJArrestingProcedure": "au14ucmj-arresting-procedure",
  "AU14UCMJCriminalCode": "au14ucmj-criminal-code",
  "AU14UCMJOptionalCrimes": "au14ucmj-optional-crimes",
  "AU14UCMJMinorCrimes": "au14ucmj-minor-crimes",
  "AU14UCMJMajorCrimes": "au14ucmj-major-crimes",
  "AU14UCMJCapitalCrimes": "au14ucmj-capital-crimes",
  "AU14UCMJPrecautionaryCharges": "au14ucmj-precautionary-charges",
  "AU14UCMJDefinitionsandGlossary": "au14ucmj-definitionsand-glossary",
  "AU14UCMJGENCON": "au14ucmjgencon",
  "AU14CCLaw": "au14cc-law",
  "AU14CCLawGeneral": "au14cc-law-general",
  "AU14CCLawCorporate": "au14cc-law-corporate",
  "AU14CCLawProcedures": "au14cc-law-procedures",
  "AU14CCLawMilitary": "au14cc-law-military",
  "AU14CCLawCriminalCode": "au14cc-law-criminal-code",
  "AU14CCLawOptionalCharges": "au14cc-law-optional-charges",
  "AU14CCLawMinorCrimes": "au14cc-law-minor-crimes",
  "AU14CCLawArmsControl": "au14cc-law-arms-control",
  "AU14CCLawMajorCrimes": "au14cc-law-major-crimes",
  "AU14CCLawCapitalCrimes": "au14cc-law-capital-crimes",
  "AU14CCLawPrecautionary": "au14cc-law-precautionary",
  "AU14CCLawEmergency": "au14cc-law-emergency",
  "AU14Comms": "au14comms",
  "AU14CommsFirstNet": "au14comms-first-net",
  "AU14CommsANPRC": "au14comms-anprc",
  "AU14CommsHeadsets": "au14comms-headsets",
  "AU14CommsVoiceProcedure": "au14comms-voice-procedure",
  "AU14CommsQuickRef": "au14comms-quick-ref",
  "References": "references",
  "Chemicals": "chemicals",
  "Elements": "elements",
  "Medicine": "medicine",
  "Narcotics": "narcotics",
  "Pyrotechnic": "pyrotechnic",
  "Toxins": "toxins",
  "Foods": "foods",
  "Botanical": "botanical",
  "Biological": "biological",
  "Special": "special",
  "Others": "others",
  "Drinks": "drinks",
  "FoodRecipes": "food-recipes",
  "PizzaRecipes": "pizza-recipes",
  "SavoryRecipes": "savory-recipes",
  "BreadRecipes": "bread-recipes",
  "BreakfastRecipes": "breakfast-recipes",
  "MothRecipes": "moth-recipes",
  "PastaRecipes": "pasta-recipes",
  "DessertRecipes": "dessert-recipes",
  "SoupRecipes": "soup-recipes",
  "PieRecipes": "pie-recipes",
  "BarsAndCookiesRecipes": "bars-and-cookies-recipes",
  "CakeRecipes": "cake-recipes",
  "SaladRecipes": "salad-recipes",
  "OtherRecipes": "other-recipes",
  "MedicinalRecipes": "medicinal-recipes",
  "SecretRecipes": "secret-recipes",
  "Writing": "writing"
};

export const marinesGuideSlugsToMeta: Record<string, GuideMeta> = {
  "new-player": {
    "title": "Primeros pasos",
    "slug": "new-player"
  },
  "controls": {
    "title": "Controles",
    "slug": "controls"
  },
  "radio": {
    "title": "Canales de voz y texto",
    "slug": "radio"
  },
  "character-creation": {
    "title": "Consejos importantes para crear tu personaje",
    "slug": "character-creation"
  },
  "your-first-character": {
    "title": "Los capitanes y los payasos",
    "slug": "your-first-character"
  },
  "species": {
    "title": "Especies",
    "slug": "species"
  },
  "arachnid": {
    "title": "Arácnidos",
    "slug": "arachnid"
  },
  "diona": {
    "title": "Diona",
    "slug": "diona"
  },
  "dwarf": {
    "title": "Enanos",
    "slug": "dwarf"
  },
  "human": {
    "title": "Humanos",
    "slug": "human"
  },
  "moth": {
    "title": "Personas polilla",
    "slug": "moth"
  },
  "reptilian": {
    "title": "Reptilianos",
    "slug": "reptilian"
  },
  "slime-person": {
    "title": "Personas de limo",
    "slug": "slime-person"
  },
  "vox": {
    "title": "Vox",
    "slug": "vox"
  },
  "ss14": {
    "title": "Space Station 14",
    "slug": "ss14"
  },
  "jobs": {
    "title": "Trabajos",
    "slug": "jobs"
  },
  "service": {
    "title": "Servicios",
    "slug": "service"
  },
  "bartender": {
    "title": "Camarero",
    "slug": "bartender"
  },
  "botany": {
    "title": "Botánica",
    "slug": "botany"
  },
  "chef": {
    "title": "Chef",
    "slug": "chef"
  },
  "janitorial": {
    "title": "Conserjería",
    "slug": "janitorial"
  },
  "cargo": {
    "title": "Carga",
    "slug": "cargo"
  },
  "cargo-bounties": {
    "title": "Recompensas de carga",
    "slug": "cargo-bounties"
  },
  "salvage": {
    "title": "Rescate",
    "slug": "salvage"
  },
  "medical": {
    "title": "Medicina",
    "slug": "medical"
  },
  "medical-doctor": {
    "title": "Médico",
    "slug": "medical-doctor"
  },
  "chemist": {
    "title": "Químico",
    "slug": "chemist"
  },
  "botanicals": {
    "title": "Productos botánicos",
    "slug": "botanicals"
  },
  "advanced-brute": {
    "title": "Sustancias especializadas contra traumatismos",
    "slug": "advanced-brute"
  },
  "cloning": {
    "title": "Clonación",
    "slug": "cloning"
  },
  "cryogenics": {
    "title": "Criogenia",
    "slug": "cryogenics"
  },
  "science": {
    "title": "Ciencia",
    "slug": "science"
  },
  "technologies": {
    "title": "Tecnologías",
    "slug": "technologies"
  },
  "anomalous-research": {
    "title": "Investigación anómala",
    "slug": "anomalous-research"
  },
  "ape": {
    "title": "A.P.E.",
    "slug": "ape"
  },
  "scanners-and-vessels": {
    "title": "Escáner de anomalías",
    "slug": "scanners-and-vessels"
  },
  "xenoarchaeology": {
    "title": "Xenoarqueología",
    "slug": "xenoarchaeology"
  },
  "artifact-reports": {
    "title": "Informes de artefactos",
    "slug": "artifact-reports"
  },
  "robotics": {
    "title": "Robótica",
    "slug": "robotics"
  },
  "cyborgs": {
    "title": "Cíborgs",
    "slug": "cyborgs"
  },
  "engineering": {
    "title": "Ingeniería",
    "slug": "engineering"
  },
  "construction": {
    "title": "Construcción",
    "slug": "construction"
  },
  "airlocks": {
    "title": "Esclusas",
    "slug": "airlocks"
  },
  "airlock-security": {
    "title": "Mejoras de esclusas",
    "slug": "airlock-security"
  },
  "expanding-repairing-station": {
    "title": "Ampliación y reparación de estaciones",
    "slug": "expanding-repairing-station"
  },
  "wire-panels": {
    "title": "Paneles de cableado",
    "slug": "wire-panels"
  },
  "power": {
    "title": "Energía",
    "slug": "power"
  },
  "generators": {
    "title": "Generadores",
    "slug": "generators"
  },
  "portable-generator": {
    "title": "Generadores portátiles",
    "slug": "portable-generator"
  },
  "ame": {
    "title": "Motor de antimateria (AME)",
    "slug": "ame"
  },
  "singularity-tesla-engine": {
    "title": "Motor de singularidad / motor Tesla",
    "slug": "singularity-tesla-engine"
  },
  "singularity-engine": {
    "title": "Motor de singularidad",
    "slug": "singularity-engine"
  },
  "tesla-engine": {
    "title": "Motor Tesla",
    "slug": "tesla-engine"
  },
  "teg": {
    "title": "Generador termoeléctrico (TEG)",
    "slug": "teg"
  },
  "rtg": {
    "title": "Generador termoeléctrico de radioisótopos (RTG)",
    "slug": "rtg"
  },
  "solar-panels": {
    "title": "Paneles solares",
    "slug": "solar-panels"
  },
  "inspecting-power": {
    "title": "Inspección de redes eléctricas",
    "slug": "inspecting-power"
  },
  "power-storage": {
    "title": "Almacenamiento de energía",
    "slug": "power-storage"
  },
  "ramping": {
    "title": "Rampa de potencia",
    "slug": "ramping"
  },
  "voltage-networks": {
    "title": "Redes de tensión",
    "slug": "voltage-networks"
  },
  "atmospherics": {
    "title": "Atmósfera",
    "slug": "atmospherics"
  },
  "gas-manipulation": {
    "title": "Manipulación de gases",
    "slug": "gas-manipulation"
  },
  "atmosphere-in-out": {
    "title": "Entrada y salida de atmósfera",
    "slug": "atmosphere-in-out"
  },
  "air-vent": {
    "title": "Conducto de ventilación",
    "slug": "air-vent"
  },
  "passive-vent": {
    "title": "Conducto de ventilación pasivo",
    "slug": "passive-vent"
  },
  "air-injector": {
    "title": "Inyector de aire",
    "slug": "air-injector"
  },
  "air-scrubber": {
    "title": "Depurador de aire",
    "slug": "air-scrubber"
  },
  "portable-scrubber": {
    "title": "Depurador portátil",
    "slug": "portable-scrubber"
  },
  "pipes": {
    "title": "Tuberías",
    "slug": "pipes"
  },
  "pumps": {
    "title": "Bombas",
    "slug": "pumps"
  },
  "valves": {
    "title": "Válvulas",
    "slug": "valves"
  },
  "manual-valve": {
    "title": "Válvula manual",
    "slug": "manual-valve"
  },
  "signal-valve": {
    "title": "Válvula de señal",
    "slug": "signal-valve"
  },
  "pneumatic-valve": {
    "title": "Válvula neumática",
    "slug": "pneumatic-valve"
  },
  "passive-gate": {
    "title": "Válvula pasiva",
    "slug": "passive-gate"
  },
  "pressure-regulator": {
    "title": "Regulador de presión de entrada",
    "slug": "pressure-regulator"
  },
  "mixing-and-filtering": {
    "title": "Mezcla y filtrado",
    "slug": "mixing-and-filtering"
  },
  "gas-canisters": {
    "title": "Bombonas de gas",
    "slug": "gas-canisters"
  },
  "thermomachines": {
    "title": "Termomáquinas",
    "slug": "thermomachines"
  },
  "radiators": {
    "title": "Radiadores",
    "slug": "radiators"
  },
  "gas-condensing": {
    "title": "Condensación de gases",
    "slug": "gas-condensing"
  },
  "atmospherics-systems": {
    "title": "Sistemas atmosféricos",
    "slug": "atmospherics-systems"
  },
  "pipe-networks": {
    "title": "Redes de tuberías",
    "slug": "pipe-networks"
  },
  "device-monitoring-and-control": {
    "title": "Supervisión y control de dispositivos",
    "slug": "device-monitoring-and-control"
  },
  "air-alarms": {
    "title": "Alarmas atmosféricas",
    "slug": "air-alarms"
  },
  "atmospheric-alerts-computer": {
    "title": "Ordenador de alertas atmosféricas",
    "slug": "atmospheric-alerts-computer"
  },
  "atmospheric-network-monitor": {
    "title": "Monitor de la red atmosférica",
    "slug": "atmospheric-network-monitor"
  },
  "fire-and-gas-control": {
    "title": "Control de incendios y gases",
    "slug": "fire-and-gas-control"
  },
  "gas-mining-and-storage": {
    "title": "Extracción y almacenamiento de gases",
    "slug": "gas-mining-and-storage"
  },
  "atmospheric-upsets": {
    "title": "Alteraciones atmosféricas",
    "slug": "atmospheric-upsets"
  },
  "fires": {
    "title": "Incendios",
    "slug": "fires"
  },
  "spacing": {
    "title": "Despresurización",
    "slug": "spacing"
  },
  "atmos-tools": {
    "title": "Herramientas de Atmósfera",
    "slug": "atmos-tools"
  },
  "gasses": {
    "title": "Gases",
    "slug": "gasses"
  },
  "shuttle-craft": {
    "title": "Lanzaderas",
    "slug": "shuttle-craft"
  },
  "networking": {
    "title": "Redes",
    "slug": "networking"
  },
  "access-configurator": {
    "title": "Configurador de accesos",
    "slug": "access-configurator"
  },
  "security": {
    "title": "Seguridad",
    "slug": "security"
  },
  "forensics": {
    "title": "Ciencia forense",
    "slug": "forensics"
  },
  "defusal": {
    "title": "Desactivación de bombas grandes",
    "slug": "defusal"
  },
  "criminal-records": {
    "title": "Antecedentes penales",
    "slug": "criminal-records"
  },
  "space-law": {
    "title": "Ley espacial",
    "slug": "space-law"
  },
  "space-law-crime-list": {
    "title": "Ley espacial: lista de delitos",
    "slug": "space-law-crime-list"
  },
  "command": {
    "title": "Mando",
    "slug": "command"
  },
  "survival": {
    "title": "Supervivencia",
    "slug": "survival"
  },
  "antagonists": {
    "title": "Antagonistas",
    "slug": "antagonists"
  },
  "traitors": {
    "title": "Traidores",
    "slug": "traitors"
  },
  "thieves": {
    "title": "Ladrones",
    "slug": "thieves"
  },
  "revolutionaries": {
    "title": "Revolucionarios",
    "slug": "revolutionaries"
  },
  "nuclear-operatives": {
    "title": "Operativos nucleares",
    "slug": "nuclear-operatives"
  },
  "space-ninja": {
    "title": "Ninja espacial",
    "slug": "space-ninja"
  },
  "wizard": {
    "title": "El mago",
    "slug": "wizard"
  },
  "zombies": {
    "title": "Zombis",
    "slug": "zombies"
  },
  "minor-antagonists": {
    "title": "Antagonistas menores",
    "slug": "minor-antagonists"
  },
  "glossary": {
    "title": "Glosario",
    "slug": "glossary"
  },
  "rmc14": {
    "title": "Guía Colonial Marines",
    "slug": "rmc14"
  },
  "rmc-guide-new-player": {
    "title": "Guías para nuevos jugadores",
    "slug": "rmc-guide-new-player"
  },
  "rmc-guide-role-rifleman": {
    "title": "Manual básico del fusilero de la UNMC",
    "slug": "rmc-guide-role-rifleman"
  },
  "rmc-guide-role-drone": {
    "title": "¡Acabas de nacer en la Colmena!",
    "slug": "rmc-guide-role-drone"
  },
  "rmc-guide-marine-roles": {
    "title": "Guía de CMU",
    "slug": "rmc-guide-marine-roles"
  },
  "rmc-survivor": {
    "title": "Survivor",
    "slug": "rmc-survivor"
  },
  "rmc-medical": {
    "title": "Medicina",
    "slug": "rmc-medical"
  },
  "au14medical-v2": {
    "title": "Medicina V2",
    "slug": "au14medical-v2"
  },
  "rmc-requisitions": {
    "title": "Requisiciones",
    "slug": "rmc-requisitions"
  },
  "rmc-intel": {
    "title": "Inteligencia",
    "slug": "rmc-intel"
  },
  "rmc-guide-role-military-police": {
    "title": "Military Police",
    "slug": "rmc-guide-role-military-police"
  },
  "rmc-guide-role-combat-technician": {
    "title": "Técnico de combate",
    "slug": "rmc-guide-role-combat-technician"
  },
  "rmc-guide-role-maintenance-technician": {
    "title": "Maintenance Technician",
    "slug": "rmc-guide-role-maintenance-technician"
  },
  "rmc-guide-role-sgo": {
    "title": "La smartgun ML66A y tú: introducción",
    "slug": "rmc-guide-role-sgo"
  },
  "rmc-guide-command-roles": {
    "title": "Who is in Command?",
    "slug": "rmc-guide-command-roles"
  },
  "rmc-guide-role-spec": {
    "title": "Recursos de élite de la UNMC",
    "slug": "rmc-guide-role-spec"
  },
  "rmc-guide-role-spec-demo": {
    "title": "Especialista en demoliciones: «Antitodo» (SADAR)",
    "slug": "rmc-guide-role-spec-demo"
  },
  "rmc-guide-role-spec-grenadier": {
    "title": "Especialista granadero pesado: «Fan de Michael Bay»",
    "slug": "rmc-guide-role-spec-grenadier"
  },
  "rmc-guide-role-spec-scout": {
    "title": "Especialista explorador: el cazador silencioso",
    "slug": "rmc-guide-role-spec-scout"
  },
  "rmc-guide-role-spec-sniper": {
    "title": "Especialista francotirador: la solución a larga distancia",
    "slug": "rmc-guide-role-spec-sniper"
  },
  "rmc-guide-role-cas": {
    "title": "Guía de operaciones con naves de descenso",
    "slug": "rmc-guide-role-cas"
  },
  "rmc-guide-marine-communications": {
    "title": "Comunicaciones de los marines",
    "slug": "rmc-guide-marine-communications"
  },
  "rmc-guide-corporate-liaison": {
    "title": "Corporate Liaison",
    "slug": "rmc-guide-corporate-liaison"
  },
  "rmc-guide-squad-leader": {
    "title": "Liderazgo de escuadrón 101",
    "slug": "rmc-guide-squad-leader"
  },
  "rmc-guide-marine-structures": {
    "title": "Guía de CMU",
    "slug": "rmc-guide-marine-structures"
  },
  "rmc-guide-communications-towers": {
    "title": "Comms and Sensors",
    "slug": "rmc-guide-communications-towers"
  },
  "rmc-guide-role-mortar": {
    "title": "Operaciones con mortero: guía rápida",
    "slug": "rmc-guide-role-mortar"
  },
  "rmc-guide-xenonid-roles": {
    "title": "Xenonid Castes",
    "slug": "rmc-guide-xenonid-roles"
  },
  "rmc-guide-xenonid-t1": {
    "title": "Tier 1 Xenonids",
    "slug": "rmc-guide-xenonid-t1"
  },
  "rmc-guide-role-defender": {
    "title": "Defensor, nivel 1",
    "slug": "rmc-guide-role-defender"
  },
  "rmc-guide-role-sentinel": {
    "title": "Centinela, nivel 1",
    "slug": "rmc-guide-role-sentinel"
  },
  "rmc-guide-role-runner": {
    "title": "Corredor, nivel 1",
    "slug": "rmc-guide-role-runner"
  },
  "rmc-guide-xenonid-t2": {
    "title": "Tier 2 Xenonids",
    "slug": "rmc-guide-xenonid-t2"
  },
  "rmc-guide-role-warrior": {
    "title": "Guerrero, nivel 2",
    "slug": "rmc-guide-role-warrior"
  },
  "rmc-guide-role-spitter": {
    "title": "Escupidor, nivel 2",
    "slug": "rmc-guide-role-spitter"
  },
  "rmc-guide-role-lurker": {
    "title": "Acechador, nivel 2",
    "slug": "rmc-guide-role-lurker"
  },
  "rmc-guide-role-vampire": {
    "title": "Vampiro, nivel 2",
    "slug": "rmc-guide-role-vampire"
  },
  "rmc-guide-role-hivelord": {
    "title": "Señor de la colmena, nivel 2",
    "slug": "rmc-guide-role-hivelord"
  },
  "rmc-guide-role-designer": {
    "title": "Diseñador, cepa de nivel 2",
    "slug": "rmc-guide-role-designer"
  },
  "rmc-guide-role-burrower": {
    "title": "Excavador, nivel 2",
    "slug": "rmc-guide-role-burrower"
  },
  "rmc-guide-role-carrier": {
    "title": "Portador, nivel 2",
    "slug": "rmc-guide-role-carrier"
  },
  "rmc-guide-role-eggsac": {
    "title": "Saco de huevos, nivel 2",
    "slug": "rmc-guide-role-eggsac"
  },
  "rmc-guide-xenonid-t3": {
    "title": "Tier 3 Xenonids",
    "slug": "rmc-guide-xenonid-t3"
  },
  "rmc-guide-role-crusher": {
    "title": "Triturador, nivel 3",
    "slug": "rmc-guide-role-crusher"
  },
  "rmc-guide-role-praetorian": {
    "title": "Pretoriano, nivel 3",
    "slug": "rmc-guide-role-praetorian"
  },
  "rmc-guide-role-valkyrie": {
    "title": "Valquiria, nivel 3",
    "slug": "rmc-guide-role-valkyrie"
  },
  "rmc-guide-role-oppressor": {
    "title": "Opresor, nivel 3",
    "slug": "rmc-guide-role-oppressor"
  },
  "rmc-guide-role-vanguard": {
    "title": "Vanguardia, nivel 3",
    "slug": "rmc-guide-role-vanguard"
  },
  "rmc-guide-role-ravager": {
    "title": "Devastador nivel 3",
    "slug": "rmc-guide-role-ravager"
  },
  "rmc-guide-role-boiler": {
    "title": "Bombardero, nivel 3",
    "slug": "rmc-guide-role-boiler"
  },
  "rmc-guide-role-sapper": {
    "title": "Bombardero, nivel 3",
    "slug": "rmc-guide-role-sapper"
  },
  "rmc-guide-role-queen": {
    "title": "¡Has ascendido al trono de la Colmena!",
    "slug": "rmc-guide-role-queen"
  },
  "rmc-guide-role-parasite": {
    "title": "Parásito",
    "slug": "rmc-guide-role-parasite"
  },
  "rmc-guide-xenonid-structures": {
    "title": "Guía de CMU",
    "slug": "rmc-guide-xenonid-structures"
  },
  "rmc-guide-hive-structures": {
    "title": "Estructuras de la Colmena",
    "slug": "rmc-guide-hive-structures"
  },
  "rmc-guide-resin-holes": {
    "title": "Agujeros de resina",
    "slug": "rmc-guide-resin-holes"
  },
  "rmc-guide-xenonid-map": {
    "title": "Iconos tácticos de mapa de los xenónidos",
    "slug": "rmc-guide-xenonid-map"
  },
  "rmc-guide-food": {
    "title": "Recetas para microondas",
    "slug": "rmc-guide-food"
  },
  "rmc-guide-drinks": {
    "title": "Bebidas",
    "slug": "rmc-guide-drinks"
  },
  "cmu-research-index": {
    "title": "Research",
    "slug": "cmu-research-index"
  },
  "cmu-research": {
    "title": "Chemistry",
    "slug": "cmu-research"
  },
  "cmurdt": {
    "title": "The Research Data Terminal",
    "slug": "cmurdt"
  },
  "cmuxrf": {
    "title": "The XRF Scanner",
    "slug": "cmuxrf"
  },
  "cmusim": {
    "title": "The Synthesis Simulator",
    "slug": "cmusim"
  },
  "cmu-botany": {
    "title": "Research Hydroponics",
    "slug": "cmu-botany"
  },
  "rmc-chemicals": {
    "title": "Sustancias químicas",
    "slug": "rmc-chemicals"
  },
  "rmc-medicine": {
    "title": "Medicamentos esenciales",
    "slug": "rmc-medicine"
  },
  "rmc-ordinance-chemicals": {
    "title": "Combustible para incinerador",
    "slug": "rmc-ordinance-chemicals"
  },
  "rmc-overview": {
    "title": "Resumen de reglas",
    "slug": "rmc-overview"
  },
  "au14rules-zero-tolerance": {
    "title": "REGLAS DE TOLERANCIA CERO",
    "slug": "au14rules-zero-tolerance"
  },
  "au14rules-general": {
    "title": "REGLAS GENERALES",
    "slug": "au14rules-general"
  },
  "au14rules-roleplay": {
    "title": "REGLAS DE INTERPRETACIÓN DE ROLES",
    "slug": "au14rules-roleplay"
  },
  "au14high-roleplay-roles": {
    "title": "Roles de interpretación exigente",
    "slug": "au14high-roleplay-roles"
  },
  "au14gamemode-rules-overview": {
    "title": "Reglas del modo de juego",
    "slug": "au14gamemode-rules-overview"
  },
  "au14gamemode-rules-insurgency": {
    "title": "REGLAS DE INSURGENCIA",
    "slug": "au14gamemode-rules-insurgency"
  },
  "au14sop": {
    "title": "Procedimiento operativo estándar",
    "slug": "au14sop"
  },
  "au14sop-rulesof-engagement": {
    "title": "Reglas de enfrentamiento",
    "slug": "au14sop-rulesof-engagement"
  },
  "au14sop-rank-structure": {
    "title": "Estructura de rangos",
    "slug": "au14sop-rank-structure"
  },
  "au14sop-equipment-and-personnel": {
    "title": "Normas de equipo y personal",
    "slug": "au14sop-equipment-and-personnel"
  },
  "au14sop-command": {
    "title": "Reglamentos del mando",
    "slug": "au14sop-command"
  },
  "au14sop-dropshipsand-aircraft": {
    "title": "Naves de desembarco y aeronaves",
    "slug": "au14sop-dropshipsand-aircraft"
  },
  "au14sop-third-party": {
    "title": "Reglamentos para terceros",
    "slug": "au14sop-third-party"
  },
  "au14sop-deployment": {
    "title": "Reglamentos de despliegue",
    "slug": "au14sop-deployment"
  },
  "au14sop-vehicles": {
    "title": "Vehículos y medios motorizados",
    "slug": "au14sop-vehicles"
  },
  "au14ucmj": {
    "title": "Código Uniforme de Justicia Militar",
    "slug": "au14ucmj"
  },
  "au14ucmj-law-rank-structure": {
    "title": "Jerarquía de autoridad jurídica",
    "slug": "au14ucmj-law-rank-structure"
  },
  "au14ucmj-right-to-appeal": {
    "title": "Derecho de apelación",
    "slug": "au14ucmj-right-to-appeal"
  },
  "au14ucmjnjp": {
    "title": "Sanciones extrajudiciales",
    "slug": "au14ucmjnjp"
  },
  "au14ucmj-arresting-procedure": {
    "title": "Procedimientos de arresto",
    "slug": "au14ucmj-arresting-procedure"
  },
  "au14ucmj-criminal-code": {
    "title": "Código penal",
    "slug": "au14ucmj-criminal-code"
  },
  "au14ucmj-optional-crimes": {
    "title": "Delitos adicionales",
    "slug": "au14ucmj-optional-crimes"
  },
  "au14ucmj-minor-crimes": {
    "title": "Delitos leves",
    "slug": "au14ucmj-minor-crimes"
  },
  "au14ucmj-major-crimes": {
    "title": "Delitos graves",
    "slug": "au14ucmj-major-crimes"
  },
  "au14ucmj-capital-crimes": {
    "title": "Delitos capitales",
    "slug": "au14ucmj-capital-crimes"
  },
  "au14ucmj-precautionary-charges": {
    "title": "Medidas cautelares",
    "slug": "au14ucmj-precautionary-charges"
  },
  "au14ucmj-definitionsand-glossary": {
    "title": "Definiciones y glosario",
    "slug": "au14ucmj-definitionsand-glossary"
  },
  "au14ucmjgencon": {
    "title": "Los Convenios de Ginebra del 12 de agosto de 2106",
    "slug": "au14ucmjgencon"
  },
  "au14cc-law": {
    "title": "Código Civil Colonial",
    "slug": "au14cc-law"
  },
  "au14cc-law-general": {
    "title": "DISPOSICIONES GENERALES",
    "slug": "au14cc-law-general"
  },
  "au14cc-law-corporate": {
    "title": "JURISDICCIÓN CORPORATIVA Y FRONTERIZA",
    "slug": "au14cc-law-corporate"
  },
  "au14cc-law-procedures": {
    "title": "CITACIONES CIVILES",
    "slug": "au14cc-law-procedures"
  },
  "au14cc-law-military": {
    "title": "PRESENCIA MILITAR",
    "slug": "au14cc-law-military"
  },
  "au14cc-law-criminal-code": {
    "title": "CÓDIGO PENAL",
    "slug": "au14cc-law-criminal-code"
  },
  "au14cc-law-optional-charges": {
    "title": "CARGOS ADICIONALES OPCIONALES",
    "slug": "au14cc-law-optional-charges"
  },
  "au14cc-law-minor-crimes": {
    "title": "DELITOS LEVES",
    "slug": "au14cc-law-minor-crimes"
  },
  "au14cc-law-arms-control": {
    "title": "CONTROL DE ARMAS & LEGISLACIÓN",
    "slug": "au14cc-law-arms-control"
  },
  "au14cc-law-major-crimes": {
    "title": "DELITOS GRAVES",
    "slug": "au14cc-law-major-crimes"
  },
  "au14cc-law-capital-crimes": {
    "title": "DELITOS CAPITALES",
    "slug": "au14cc-law-capital-crimes"
  },
  "au14cc-law-precautionary": {
    "title": "RECLUSIÓN PREVENTIVA",
    "slug": "au14cc-law-precautionary"
  },
  "au14cc-law-emergency": {
    "title": "FACULTADES DE EMERGENCIA",
    "slug": "au14cc-law-emergency"
  },
  "au14comms": {
    "title": "Referencia de comunicaciones",
    "slug": "au14comms"
  },
  "au14comms-first-net": {
    "title": "Primer acceso a la red",
    "slug": "au14comms-first-net"
  },
  "au14comms-anprc": {
    "title": "Radio AN/PRC-117G",
    "slug": "au14comms-anprc"
  },
  "au14comms-headsets": {
    "title": "Auriculares de campaña",
    "slug": "au14comms-headsets"
  },
  "au14comms-voice-procedure": {
    "title": "Procedimiento radiotelefónico",
    "slug": "au14comms-voice-procedure"
  },
  "au14comms-quick-ref": {
    "title": "Referencia rápida de comunicaciones",
    "slug": "au14comms-quick-ref"
  },
  "references": {
    "title": "Referencias",
    "slug": "references"
  },
  "chemicals": {
    "title": "Sustancias químicas",
    "slug": "chemicals"
  },
  "elements": {
    "title": "Elementos",
    "slug": "elements"
  },
  "medicine": {
    "title": "Medicamentos esenciales",
    "slug": "medicine"
  },
  "narcotics": {
    "title": "Narcóticos",
    "slug": "narcotics"
  },
  "pyrotechnic": {
    "title": "Pirotecnia",
    "slug": "pyrotechnic"
  },
  "toxins": {
    "title": "Toxinas",
    "slug": "toxins"
  },
  "foods": {
    "title": "Alimentos",
    "slug": "foods"
  },
  "botanical": {
    "title": "Productos botánicos",
    "slug": "botanical"
  },
  "biological": {
    "title": "Biológicos",
    "slug": "biological"
  },
  "special": {
    "title": "Especiales",
    "slug": "special"
  },
  "others": {
    "title": "Otros",
    "slug": "others"
  },
  "drinks": {
    "title": "Bebidas",
    "slug": "drinks"
  },
  "food-recipes": {
    "title": "Recetas para microondas",
    "slug": "food-recipes"
  },
  "pizza-recipes": {
    "title": "Pizzas",
    "slug": "pizza-recipes"
  },
  "savory-recipes": {
    "title": "Recetas saladas",
    "slug": "savory-recipes"
  },
  "bread-recipes": {
    "title": "Panes",
    "slug": "bread-recipes"
  },
  "breakfast-recipes": {
    "title": "Recetas de desayuno",
    "slug": "breakfast-recipes"
  },
  "moth-recipes": {
    "title": "Comida para polillas",
    "slug": "moth-recipes"
  },
  "pasta-recipes": {
    "title": "Pastas & fideos",
    "slug": "pasta-recipes"
  },
  "dessert-recipes": {
    "title": "Repostería & postres",
    "slug": "dessert-recipes"
  },
  "soup-recipes": {
    "title": "Sopas & guisos",
    "slug": "soup-recipes"
  },
  "pie-recipes": {
    "title": "Tartas & tartaletas",
    "slug": "pie-recipes"
  },
  "bars-and-cookies-recipes": {
    "title": "Barritas & galletas",
    "slug": "bars-and-cookies-recipes"
  },
  "cake-recipes": {
    "title": "Pasteles",
    "slug": "cake-recipes"
  },
  "salad-recipes": {
    "title": "Ensaladas",
    "slug": "salad-recipes"
  },
  "other-recipes": {
    "title": "Otras recetas",
    "slug": "other-recipes"
  },
  "medicinal-recipes": {
    "title": "Recetas medicinales",
    "slug": "medicinal-recipes"
  },
  "secret-recipes": {
    "title": "Recetas secretas",
    "slug": "secret-recipes"
  },
  "writing": {
    "title": "Escritura",
    "slug": "writing"
  }
};
