// AUTO-GENERATED by scripts/generate-guides.mjs — DO NOT EDIT
// Lightweight lookup maps for client components (no guide content)
// Run: npm run generate-guides

import type { GuideMeta } from "./guide-types";

export const monolithGuideIdToSlug: Record<string, string> = {
  "NewPlayer": "new-player",
  "Controls": "controls",
  "Radio": "radio",
  "CharacterCreation": "character-creation",
  "YourFirstCharacter": "your-first-character",
  "Species": "species",
  "Arachnid": "arachnid",
  "Diona": "diona",
  "Dwarf": "dwarf",
  "Human": "human",
  "Moth": "moth",
  "Reptilian": "reptilian",
  "SlimePerson": "slime-person",
  "Vox": "vox",
  "Goblin": "goblin",
  "Vulpkanin": "vulpkanin",
  "Harpy": "harpy",
  "Felinid": "felinid",
  "Oni": "oni",
  "Chitinid": "chitinid",
  "Resomi": "resomi",
  "Protogen": "protogen",
  "IPC": "ipc",
  "Rodentia": "rodentia",
  "Tajaran": "tajaran",
  "Hydrakin": "hydrakin",
  "Flight": "flight",
  "StartingGear": "starting-gear",
  "NF14": "nf14",
  "Bank": "bank",
  "Hiring": "hiring",
  "Piloting": "piloting",
  "Survival": "survival",
  "SectorTopology": "sector-topology",
  "Expeditions": "expeditions",
  "MobsExpeditionGuideAberrantFlesh": "mobs-expedition-guide-aberrant-flesh",
  "MobsExpeditionGuideArgocytes": "mobs-expedition-guide-argocytes",
  "MobsExpeditionGuideBloodCult": "mobs-expedition-guide-blood-cult",
  "MobsExpeditionGuideCarps": "mobs-expedition-guide-carps",
  "MobsExpeditionGuideDinosaurs": "mobs-expedition-guide-dinosaurs",
  "MobsExpeditionGuideExplorers": "mobs-expedition-guide-explorers",
  "MobsExpeditionGuideMercenaries": "mobs-expedition-guide-mercenaries",
  "MobsExpeditionGuideGangers": "mobs-expedition-guide-gangers",
  "MobsExpeditionGuideSilicons": "mobs-expedition-guide-silicons",
  "MobsExpeditionGuideSyndicate": "mobs-expedition-guide-syndicate",
  "MobsExpeditionGuideXenos": "mobs-expedition-guide-xenos",
  "CargoHauling": "cargo-hauling",
  "Shipyard": "shipyard",
  "ShipyardNFROperation": "shipyard-nfr-operation",
  "ShipyardArgent": "shipyard-argent",
  "ShipyardJudiciary": "shipyard-judiciary",
  "ShipyardSabine": "shipyard-sabine",
  "ShipyardTakeaway": "shipyard-takeaway",
  "ShipyardMotleyAnne": "shipyard-motley-anne",
  "ShipyardFenrir": "shipyard-fenrir",
  "WeaponsSystems": "weapons-systems",
  "BallisticsTable": "ballistics-table",
  "EnergyTable": "energy-table",
  "MissilesTable": "missiles-table",
  "Creatures": "creatures",
  "CorticalBorerGuide": "cortical-borer-guide",
  "Letoferol": "letoferol",
  "MonoMisc": "mono-misc",
  "GridClaimer": "grid-claimer",
  "ArmorExplanation": "armor-explanation",
  "Jobs": "jobs",
  "Service": "service",
  "Bartender": "bartender",
  "Botany": "botany",
  "Chef": "chef",
  "Janitorial": "janitorial",
  "Medical": "medical",
  "DirectorOfCare": "director-of-care",
  "MedicalDoctor": "medical-doctor",
  "Chemist": "chemist",
  "Botanicals": "botanicals",
  "AdvancedBrute": "advanced-brute",
  "Cloning": "cloning",
  "Cryogenics": "cryogenics",
  "Surgery": "surgery",
  "PartManipulation": "part-manipulation",
  "OrganManipulation": "organ-manipulation",
  "UtilitySurgeries": "utility-surgeries",
  "MedicalBounties": "medical-bounties",
  "Science": "science",
  "Technologies": "technologies",
  "AnomalousResearch": "anomalous-research",
  "APE": "ape",
  "ScannersAndVessels": "scanners-and-vessels",
  "Xenoarchaeology": "xenoarchaeology",
  "ArtifactReports": "artifact-reports",
  "Robotics": "robotics",
  "Cyborgs": "cyborgs",
  "MechsBase": "mechs-base",
  "S1Mechs": "s1mechs",
  "S2Mechs": "s2mechs",
  "S4Mechs": "s4mechs",
  "MachineUpgrading": "machine-upgrading",
  "Engineering": "engineering",
  "Construction": "construction",
  "Airlocks": "airlocks",
  "AirlockSecurity": "airlock-security",
  "ExpandingRepairingStation": "expanding-repairing-station",
  "WirePanels": "wire-panels",
  "Power": "power",
  "Generators": "generators",
  "PortableGenerator": "portable-generator",
  "AME": "ame",
  "SingularityTeslaEngine": "singularity-tesla-engine",
  "SingularityEngine": "singularity-engine",
  "TeslaEngine": "tesla-engine",
  "NuclearReactor": "nuclear-reactor",
  "NuclearMaterials": "nuclear-materials",
  "TEG": "teg",
  "RTG": "rtg",
  "SolarPanels": "solar-panels",
  "InspectingPower": "inspecting-power",
  "PowerStorage": "power-storage",
  "Ramping": "ramping",
  "VoltageNetworks": "voltage-networks",
  "Atmospherics": "atmospherics",
  "GasManipulation": "gas-manipulation",
  "AtmosphereInOut": "atmosphere-in-out",
  "AirVent": "air-vent",
  "PassiveVent": "passive-vent",
  "AirInjector": "air-injector",
  "AirScrubber": "air-scrubber",
  "PortableScrubber": "portable-scrubber",
  "Pipes": "pipes",
  "Pumps": "pumps",
  "Valves": "valves",
  "ManualValve": "manual-valve",
  "SignalValve": "signal-valve",
  "PneumaticValve": "pneumatic-valve",
  "PassiveGate": "passive-gate",
  "PressureRegulator": "pressure-regulator",
  "MixingAndFiltering": "mixing-and-filtering",
  "GasCanisters": "gas-canisters",
  "Thermomachines": "thermomachines",
  "Radiators": "radiators",
  "GasCondensing": "gas-condensing",
  "AtmosphericsSystems": "atmospherics-systems",
  "PipeNetworks": "pipe-networks",
  "DeviceMonitoringAndControl": "device-monitoring-and-control",
  "AirAlarms": "air-alarms",
  "AtmosphericAlertsComputer": "atmospheric-alerts-computer",
  "AtmosphericNetworkMonitor": "atmospheric-network-monitor",
  "FireAndGasControl": "fire-and-gas-control",
  "GasMiningAndStorage": "gas-mining-and-storage",
  "AtmosphericUpsets": "atmospheric-upsets",
  "Fires": "fires",
  "Spacing": "spacing",
  "AtmosTools": "atmos-tools",
  "Gasses": "gasses",
  "GasMining": "gas-mining",
  "ShuttleCraft": "shuttle-craft",
  "Networking": "networking",
  "AccessConfigurator": "access-configurator",
  "Automation": "automation",
  "Command": "command",
  "Economy": "economy",
  "EconomyRecipes": "economy-recipes",
  "ArcFurnace": "arc-furnace",
  "Factions": "factions",
  "TSFMC_Entry": "tsfmc-entry",
  "Smuggling": "smuggling",
  "Defusal": "defusal",
  "PDV_Entry": "pdv-entry",
  "Minor_Factions": "minor-factions",
  "USSP_Entry": "ussp-entry",
  "USSP_SoP": "ussp-so-p",
  "USSP_Overview": "ussp-overview",
  "Viper_Group": "viper-group",
  "BasicLore": "basic-lore",
  "Timeline": "timeline",
  "References": "references",
  "Chemicals": "chemicals",
  "Elements": "elements",
  "Medicine": "medicine",
  "Narcotics": "narcotics",
  "Pyrotechnic": "pyrotechnic",
  "Toxins": "toxins",
  "Foods": "foods",
  "Botanical": "botanical",
  "Biological": "biological",
  "Special": "special",
  "Others": "others",
  "Drinks": "drinks",
  "FoodRecipes": "food-recipes",
  "PizzaRecipes": "pizza-recipes",
  "SavoryRecipes": "savory-recipes",
  "BreadRecipes": "bread-recipes",
  "BreakfastRecipes": "breakfast-recipes",
  "MothRecipes": "moth-recipes",
  "PastaRecipes": "pasta-recipes",
  "DessertRecipes": "dessert-recipes",
  "SoupRecipes": "soup-recipes",
  "PieRecipes": "pie-recipes",
  "BarsAndCookiesRecipes": "bars-and-cookies-recipes",
  "CakeRecipes": "cake-recipes",
  "SaladRecipes": "salad-recipes",
  "OtherRecipes": "other-recipes",
  "MedicinalRecipes": "medicinal-recipes",
  "SecretRecipes": "secret-recipes",
  "Writing": "writing",
  "MedicalRecipes": "medical-recipes",
  "MonolithRuleset": "monolith-ruleset",
  "MonolithRuleCoreOneCommonSense": "monolith-rule-core-one-common-sense",
  "MonolithRuleCoreTwoRespect": "monolith-rule-core-two-respect",
  "MonolithRuleCoreThreeCheatingExploits": "monolith-rule-core-three-cheating-exploits",
  "MonolithRuleCoreFourAlternativeAccounts": "monolith-rule-core-four-alternative-accounts",
  "MonolithRuleCoreFiveLanguages": "monolith-rule-core-five-languages",
  "MonolithRuleCoreSixAhelp": "monolith-rule-core-six-ahelp",
  "MonolithRuleCoreSevenThreatenToReport": "monolith-rule-core-seven-threaten-to-report",
  "MonolithRuleRoleplayOneBreakCharacter": "monolith-rule-roleplay-one-break-character",
  "MonolithRuleRoleplayTwoTextChat": "monolith-rule-roleplay-two-text-chat",
  "MonolithRuleRoleplayThreeProperGrammar": "monolith-rule-roleplay-three-proper-grammar",
  "MonolithRuleRoleplayFourCharacterActions": "monolith-rule-roleplay-four-character-actions",
  "MonolithRuleRoleplayFiveEroticRoleplay": "monolith-rule-roleplay-five-erotic-roleplay",
  "MonolithRuleRoleplaySixMetagame": "monolith-rule-roleplay-six-metagame",
  "MonolithRuleRoleplaySevenSafeZones": "monolith-rule-roleplay-seven-safe-zones",
  "MonolithRuleRoleplayEightFactionRoles": "monolith-rule-roleplay-eight-faction-roles",
  "MonolithRuleRoleplayNineCommandingRoles": "monolith-rule-roleplay-nine-commanding-roles",
  "MonolithRuleConflictOneRandomDeathmatch": "monolith-rule-conflict-one-random-deathmatch",
  "MonolithRuleConflictTwoNewLife": "monolith-rule-conflict-two-new-life",
  "MonolithRuleConflictThreeFairPlay": "monolith-rule-conflict-three-fair-play",
  "MonolithRuleConflictFourPortStriking": "monolith-rule-conflict-four-port-striking"
};

export const monolithGuideSlugsToMeta: Record<string, GuideMeta> = {
  "new-player": {
    "title": "Primeros pasos",
    "slug": "new-player"
  },
  "controls": {
    "title": "Controles",
    "slug": "controls"
  },
  "radio": {
    "title": "Canales de Habla y Texto",
    "slug": "radio"
  },
  "character-creation": {
    "title": "Consejos importantes para crear un personaje",
    "slug": "character-creation"
  },
  "your-first-character": {
    "title": "Los Capitanes y los Payasos",
    "slug": "your-first-character"
  },
  "species": {
    "title": "Especies",
    "slug": "species"
  },
  "arachnid": {
    "title": "Arácnidos",
    "slug": "arachnid"
  },
  "diona": {
    "title": "Diona",
    "slug": "diona"
  },
  "dwarf": {
    "title": "Enanos",
    "slug": "dwarf"
  },
  "human": {
    "title": "Humanos",
    "slug": "human"
  },
  "moth": {
    "title": "Personas polilla",
    "slug": "moth"
  },
  "reptilian": {
    "title": "Reptilianos",
    "slug": "reptilian"
  },
  "slime-person": {
    "title": "Personas Slime",
    "slug": "slime-person"
  },
  "vox": {
    "title": "Vox",
    "slug": "vox"
  },
  "goblin": {
    "title": "Goblins",
    "slug": "goblin"
  },
  "vulpkanin": {
    "title": "Vulpkanin",
    "slug": "vulpkanin"
  },
  "harpy": {
    "title": "Arpías",
    "slug": "harpy"
  },
  "felinid": {
    "title": "Felínidos",
    "slug": "felinid"
  },
  "oni": {
    "title": "Onis",
    "slug": "oni"
  },
  "chitinid": {
    "title": "Chitinid",
    "slug": "chitinid"
  },
  "resomi": {
    "title": "Resomi",
    "slug": "resomi"
  },
  "protogen": {
    "title": "Protógenos",
    "slug": "protogen"
  },
  "ipc": {
    "title": "I.P.C.",
    "slug": "ipc"
  },
  "rodentia": {
    "title": "Rodentia",
    "slug": "rodentia"
  },
  "tajaran": {
    "title": "Tajaran",
    "slug": "tajaran"
  },
  "hydrakin": {
    "title": "Hydrakin",
    "slug": "hydrakin"
  },
  "flight": {
    "title": "Vuelo",
    "slug": "flight"
  },
  "starting-gear": {
    "title": "Equipamiento Inicial",
    "slug": "starting-gear"
  },
  "nf14": {
    "title": "El Monolith llama",
    "slug": "nf14"
  },
  "bank": {
    "title": "Central Galactic Bank",
    "slug": "bank"
  },
  "hiring": {
    "title": "Contratar Tripulación",
    "slug": "hiring"
  },
  "piloting": {
    "title": "Pilotaje",
    "slug": "piloting"
  },
  "survival": {
    "title": "Supervivencia",
    "slug": "survival"
  },
  "sector-topology": {
    "title": "Topología del sector",
    "slug": "sector-topology"
  },
  "expeditions": {
    "title": "Expediciones de Salvamento",
    "slug": "expeditions"
  },
  "mobs-expedition-guide-aberrant-flesh": {
    "title": "Carne Aberrante",
    "slug": "mobs-expedition-guide-aberrant-flesh"
  },
  "mobs-expedition-guide-argocytes": {
    "title": "Argocytes",
    "slug": "mobs-expedition-guide-argocytes"
  },
  "mobs-expedition-guide-blood-cult": {
    "title": "Culto de Sangre",
    "slug": "mobs-expedition-guide-blood-cult"
  },
  "mobs-expedition-guide-carps": {
    "title": "Carps",
    "slug": "mobs-expedition-guide-carps"
  },
  "mobs-expedition-guide-dinosaurs": {
    "title": "Dinosaurios",
    "slug": "mobs-expedition-guide-dinosaurs"
  },
  "mobs-expedition-guide-explorers": {
    "title": "Exploradores",
    "slug": "mobs-expedition-guide-explorers"
  },
  "mobs-expedition-guide-mercenaries": {
    "title": "Mercenarios",
    "slug": "mobs-expedition-guide-mercenaries"
  },
  "mobs-expedition-guide-gangers": {
    "title": "Punks",
    "slug": "mobs-expedition-guide-gangers"
  },
  "mobs-expedition-guide-silicons": {
    "title": "Silicios rebeldes",
    "slug": "mobs-expedition-guide-silicons"
  },
  "mobs-expedition-guide-syndicate": {
    "title": "Fuerzas Navales del Syndicate",
    "slug": "mobs-expedition-guide-syndicate"
  },
  "mobs-expedition-guide-xenos": {
    "title": "Xenos",
    "slug": "mobs-expedition-guide-xenos"
  },
  "cargo-hauling": {
    "title": "Transporte de Carga",
    "slug": "cargo-hauling"
  },
  "shipyard": {
    "title": "Astilleros Colossus",
    "slug": "shipyard"
  },
  "shipyard-nfr-operation": {
    "title": "MANUAL DE OPERACIÓN DEL BUQUE REACTOR DE FISIÓN NUCLEAR",
    "slug": "shipyard-nfr-operation"
  },
  "shipyard-argent": {
    "title": "TRANSPORTE DE CARGA CLASE ARGENT",
    "slug": "shipyard-argent"
  },
  "shipyard-judiciary": {
    "title": "VEI CLASE JUDICIARY",
    "slug": "shipyard-judiciary"
  },
  "shipyard-sabine": {
    "title": "TRANSBORDADOR DE SALVAMENTO CLASE SABINE",
    "slug": "shipyard-sabine"
  },
  "shipyard-takeaway": {
    "title": "TRANSBORDADOR DE SERVICIO CLASE TAKEAWAY",
    "slug": "shipyard-takeaway"
  },
  "shipyard-motley-anne": {
    "title": "ASTILLERO 'MOTLEY ANNE'",
    "slug": "shipyard-motley-anne"
  },
  "shipyard-fenrir": {
    "title": "DESTRUCTOR CLASE FENRIR",
    "slug": "shipyard-fenrir"
  },
  "weapons-systems": {
    "title": "Combate Naval",
    "slug": "weapons-systems"
  },
  "ballistics-table": {
    "title": "Especificaciones de Armas Balísticas",
    "slug": "ballistics-table"
  },
  "energy-table": {
    "title": "Especificaciones de Armas de Energía",
    "slug": "energy-table"
  },
  "missiles-table": {
    "title": "Especificaciones de Armas de Misil",
    "slug": "missiles-table"
  },
  "creatures": {
    "title": "Criaturas del Sector",
    "slug": "creatures"
  },
  "cortical-borer-guide": {
    "title": "Perforador Cortical",
    "slug": "cortical-borer-guide"
  },
  "letoferol": {
    "title": "Quimeras y Letoferol",
    "slug": "letoferol"
  },
  "mono-misc": {
    "title": "Varios",
    "slug": "mono-misc"
  },
  "grid-claimer": {
    "title": "Reclamar Escombros",
    "slug": "grid-claimer"
  },
  "armor-explanation": {
    "title": "Mecánica de la Armadura",
    "slug": "armor-explanation"
  },
  "jobs": {
    "title": "Trabajos y roles",
    "slug": "jobs"
  },
  "service": {
    "title": "Servicio",
    "slug": "service"
  },
  "bartender": {
    "title": "Camarero",
    "slug": "bartender"
  },
  "botany": {
    "title": "Botánica",
    "slug": "botany"
  },
  "chef": {
    "title": "Cocinero",
    "slug": "chef"
  },
  "janitorial": {
    "title": "Conserjería",
    "slug": "janitorial"
  },
  "medical": {
    "title": "Médico",
    "slug": "medical"
  },
  "director-of-care": {
    "title": "Director de Atención",
    "slug": "director-of-care"
  },
  "medical-doctor": {
    "title": "Doctor",
    "slug": "medical-doctor"
  },
  "chemist": {
    "title": "Químico",
    "slug": "chemist"
  },
  "botanicals": {
    "title": "Plantas Medicinales",
    "slug": "botanicals"
  },
  "advanced-brute": {
    "title": "Reactivos Especializados para Daño Contuso",
    "slug": "advanced-brute"
  },
  "cloning": {
    "title": "Clonación",
    "slug": "cloning"
  },
  "cryogenics": {
    "title": "Criogénesis",
    "slug": "cryogenics"
  },
  "surgery": {
    "title": "Cirugía",
    "slug": "surgery"
  },
  "part-manipulation": {
    "title": "Manipulación de Partes",
    "slug": "part-manipulation"
  },
  "organ-manipulation": {
    "title": "Manipulación de Órganos",
    "slug": "organ-manipulation"
  },
  "utility-surgeries": {
    "title": "Cirugías de Utilidad",
    "slug": "utility-surgeries"
  },
  "medical-bounties": {
    "title": "Recompensas Médicas",
    "slug": "medical-bounties"
  },
  "science": {
    "title": "Ciencia",
    "slug": "science"
  },
  "technologies": {
    "title": "Tecnologías",
    "slug": "technologies"
  },
  "anomalous-research": {
    "title": "Investigación de Anomalías",
    "slug": "anomalous-research"
  },
  "ape": {
    "title": "A.P.E.",
    "slug": "ape"
  },
  "scanners-and-vessels": {
    "title": "Escáner de Anomalías",
    "slug": "scanners-and-vessels"
  },
  "xenoarchaeology": {
    "title": "Xenoarqueología",
    "slug": "xenoarchaeology"
  },
  "artifact-reports": {
    "title": "Informes de Artefactos",
    "slug": "artifact-reports"
  },
  "robotics": {
    "title": "Robótica",
    "slug": "robotics"
  },
  "cyborgs": {
    "title": "Cyborgs",
    "slug": "cyborgs"
  },
  "mechs-base": {
    "title": "Mechs",
    "slug": "mechs-base"
  },
  "s1mechs": {
    "title": "Mechs de Combate Serie 1",
    "slug": "s1mechs"
  },
  "s2mechs": {
    "title": "Mechs de Combate Serie 2",
    "slug": "s2mechs"
  },
  "s4mechs": {
    "title": "Mechs de Combate Serie 4",
    "slug": "s4mechs"
  },
  "machine-upgrading": {
    "title": "Actualización de Máquinas",
    "slug": "machine-upgrading"
  },
  "engineering": {
    "title": "Ingeniería",
    "slug": "engineering"
  },
  "construction": {
    "title": "Construcción",
    "slug": "construction"
  },
  "airlocks": {
    "title": "Esclusas",
    "slug": "airlocks"
  },
  "airlock-security": {
    "title": "Mejoras de Esclusas",
    "slug": "airlock-security"
  },
  "expanding-repairing-station": {
    "title": "Ampliar y Reparar Estaciones",
    "slug": "expanding-repairing-station"
  },
  "wire-panels": {
    "title": "Paneles de Cables",
    "slug": "wire-panels"
  },
  "power": {
    "title": "Energía",
    "slug": "power"
  },
  "generators": {
    "title": "Generadores",
    "slug": "generators"
  },
  "portable-generator": {
    "title": "Generadores Portátiles",
    "slug": "portable-generator"
  },
  "ame": {
    "title": "Motor de Antimateria (AME)",
    "slug": "ame"
  },
  "singularity-tesla-engine": {
    "title": "Motor de Singularidad / Tesla",
    "slug": "singularity-tesla-engine"
  },
  "singularity-engine": {
    "title": "Motor de Singularidad",
    "slug": "singularity-engine"
  },
  "tesla-engine": {
    "title": "Motor Tesla",
    "slug": "tesla-engine"
  },
  "nuclear-reactor": {
    "title": "Generador Nuclear",
    "slug": "nuclear-reactor"
  },
  "nuclear-materials": {
    "title": "Efectos de los materiales",
    "slug": "nuclear-materials"
  },
  "teg": {
    "title": "Motor Termoeléctrico (TEG)",
    "slug": "teg"
  },
  "rtg": {
    "title": "Generador Termoeléctrico de Radioisótopos (RTG)",
    "slug": "rtg"
  },
  "solar-panels": {
    "title": "Paneles Solares",
    "slug": "solar-panels"
  },
  "inspecting-power": {
    "title": "Inspección de la Red Eléctrica",
    "slug": "inspecting-power"
  },
  "power-storage": {
    "title": "Almacenamiento de Energía",
    "slug": "power-storage"
  },
  "ramping": {
    "title": "Carga Progresiva",
    "slug": "ramping"
  },
  "voltage-networks": {
    "title": "Redes de Voltaje",
    "slug": "voltage-networks"
  },
  "atmospherics": {
    "title": "Atmosférica",
    "slug": "atmospherics"
  },
  "gas-manipulation": {
    "title": "Manipulación de gases",
    "slug": "gas-manipulation"
  },
  "atmosphere-in-out": {
    "title": "Entrada y Salida de Atmósfera",
    "slug": "atmosphere-in-out"
  },
  "air-vent": {
    "title": "Ventilador de Aire",
    "slug": "air-vent"
  },
  "passive-vent": {
    "title": "Ventilación pasiva",
    "slug": "passive-vent"
  },
  "air-injector": {
    "title": "Inyector de Aire",
    "slug": "air-injector"
  },
  "air-scrubber": {
    "title": "Depurador de Aire",
    "slug": "air-scrubber"
  },
  "portable-scrubber": {
    "title": "Depurador Portátil",
    "slug": "portable-scrubber"
  },
  "pipes": {
    "title": "Tuberías",
    "slug": "pipes"
  },
  "pumps": {
    "title": "Bombas",
    "slug": "pumps"
  },
  "valves": {
    "title": "Válvulas",
    "slug": "valves"
  },
  "manual-valve": {
    "title": "Válvula Manual",
    "slug": "manual-valve"
  },
  "signal-valve": {
    "title": "Válvula de señal",
    "slug": "signal-valve"
  },
  "pneumatic-valve": {
    "title": "Válvula Neumática",
    "slug": "pneumatic-valve"
  },
  "passive-gate": {
    "title": "Compuerta pasiva",
    "slug": "passive-gate"
  },
  "pressure-regulator": {
    "title": "Regulador de Presión de Entrada",
    "slug": "pressure-regulator"
  },
  "mixing-and-filtering": {
    "title": "Mezcla y filtrado",
    "slug": "mixing-and-filtering"
  },
  "gas-canisters": {
    "title": "Cilindros de gas",
    "slug": "gas-canisters"
  },
  "thermomachines": {
    "title": "Termomáquinas",
    "slug": "thermomachines"
  },
  "radiators": {
    "title": "Radiadores",
    "slug": "radiators"
  },
  "gas-condensing": {
    "title": "Condensación de gas",
    "slug": "gas-condensing"
  },
  "atmospherics-systems": {
    "title": "Sistemas Atmosféricos",
    "slug": "atmospherics-systems"
  },
  "pipe-networks": {
    "title": "Redes de Tuberías",
    "slug": "pipe-networks"
  },
  "device-monitoring-and-control": {
    "title": "Monitorización y Control de Dispositivos",
    "slug": "device-monitoring-and-control"
  },
  "air-alarms": {
    "title": "Alarmas de Aire",
    "slug": "air-alarms"
  },
  "atmospheric-alerts-computer": {
    "title": "Computadora de Alertas Atmosféricas",
    "slug": "atmospheric-alerts-computer"
  },
  "atmospheric-network-monitor": {
    "title": "Monitor de Red Atmosférica",
    "slug": "atmospheric-network-monitor"
  },
  "fire-and-gas-control": {
    "title": "Control de Fuego y Gas",
    "slug": "fire-and-gas-control"
  },
  "gas-mining-and-storage": {
    "title": "Minería y almacenamiento de gas",
    "slug": "gas-mining-and-storage"
  },
  "atmospheric-upsets": {
    "title": "Perturbaciones Atmosféricas",
    "slug": "atmospheric-upsets"
  },
  "fires": {
    "title": "Incendios",
    "slug": "fires"
  },
  "spacing": {
    "title": "Despresurización",
    "slug": "spacing"
  },
  "atmos-tools": {
    "title": "Herramientas de Atmósferas",
    "slug": "atmos-tools"
  },
  "gasses": {
    "title": "Gases",
    "slug": "gasses"
  },
  "gas-mining": {
    "title": "Minería de Gas",
    "slug": "gas-mining"
  },
  "shuttle-craft": {
    "title": "Construcción de transbordadores",
    "slug": "shuttle-craft"
  },
  "networking": {
    "title": "Redes",
    "slug": "networking"
  },
  "access-configurator": {
    "title": "Configurador de Acceso",
    "slug": "access-configurator"
  },
  "automation": {
    "title": "Brazo Robótico",
    "slug": "automation"
  },
  "command": {
    "title": "Mando",
    "slug": "command"
  },
  "economy": {
    "title": "Economía",
    "slug": "economy"
  },
  "economy-recipes": {
    "title": "Recetas de Economía",
    "slug": "economy-recipes"
  },
  "arc-furnace": {
    "title": "Recetas del Horno de Arco",
    "slug": "arc-furnace"
  },
  "factions": {
    "title": "Facciones",
    "slug": "factions"
  },
  "tsfmc-entry": {
    "title": "TSFMC",
    "slug": "tsfmc-entry"
  },
  "smuggling": {
    "title": "Prevención del contrabando",
    "slug": "smuggling"
  },
  "defusal": {
    "title": "Desactivación de Bomba Grande",
    "slug": "defusal"
  },
  "pdv-entry": {
    "title": "PDV",
    "slug": "pdv-entry"
  },
  "minor-factions": {
    "title": "Facciones Menores",
    "slug": "minor-factions"
  },
  "ussp-entry": {
    "title": "USSP Remnants",
    "slug": "ussp-entry"
  },
  "ussp-so-p": {
    "title": "USSP SOP",
    "slug": "ussp-so-p"
  },
  "ussp-overview": {
    "title": "Descripción General de la USSP",
    "slug": "ussp-overview"
  },
  "viper-group": {
    "title": "El Grupo Viper",
    "slug": "viper-group"
  },
  "basic-lore": {
    "title": "Historia del sector",
    "slug": "basic-lore"
  },
  "timeline": {
    "title": "Historia Resumida",
    "slug": "timeline"
  },
  "references": {
    "title": "Referencias",
    "slug": "references"
  },
  "chemicals": {
    "title": "Sustancias Químicas",
    "slug": "chemicals"
  },
  "elements": {
    "title": "Elementos",
    "slug": "elements"
  },
  "medicine": {
    "title": "Medicamentos Esenciales",
    "slug": "medicine"
  },
  "narcotics": {
    "title": "Narcóticos",
    "slug": "narcotics"
  },
  "pyrotechnic": {
    "title": "Pirotécnicos",
    "slug": "pyrotechnic"
  },
  "toxins": {
    "title": "Toxinas",
    "slug": "toxins"
  },
  "foods": {
    "title": "Alimentos",
    "slug": "foods"
  },
  "botanical": {
    "title": "Plantas Medicinales",
    "slug": "botanical"
  },
  "biological": {
    "title": "Biológico",
    "slug": "biological"
  },
  "special": {
    "title": "Especiales",
    "slug": "special"
  },
  "others": {
    "title": "Otros",
    "slug": "others"
  },
  "drinks": {
    "title": "Bebidas",
    "slug": "drinks"
  },
  "food-recipes": {
    "title": "Recetas de Microondas",
    "slug": "food-recipes"
  },
  "pizza-recipes": {
    "title": "Pizzas",
    "slug": "pizza-recipes"
  },
  "savory-recipes": {
    "title": "Recetas Saladas",
    "slug": "savory-recipes"
  },
  "bread-recipes": {
    "title": "Panes",
    "slug": "bread-recipes"
  },
  "breakfast-recipes": {
    "title": "Recetas de Desayuno",
    "slug": "breakfast-recipes"
  },
  "moth-recipes": {
    "title": "Alimentos para Moth",
    "slug": "moth-recipes"
  },
  "pasta-recipes": {
    "title": "Pastas y Fideos",
    "slug": "pasta-recipes"
  },
  "dessert-recipes": {
    "title": "Pastelería y Postres",
    "slug": "dessert-recipes"
  },
  "soup-recipes": {
    "title": "Sopas y Guisos",
    "slug": "soup-recipes"
  },
  "pie-recipes": {
    "title": "Tartas y Barritas",
    "slug": "pie-recipes"
  },
  "bars-and-cookies-recipes": {
    "title": "Barritas y Galletas",
    "slug": "bars-and-cookies-recipes"
  },
  "cake-recipes": {
    "title": "Tartas",
    "slug": "cake-recipes"
  },
  "salad-recipes": {
    "title": "Ensaladas",
    "slug": "salad-recipes"
  },
  "other-recipes": {
    "title": "Otras Recetas",
    "slug": "other-recipes"
  },
  "medicinal-recipes": {
    "title": "Recetas Medicinales",
    "slug": "medicinal-recipes"
  },
  "secret-recipes": {
    "title": "Recetas Secretas",
    "slug": "secret-recipes"
  },
  "writing": {
    "title": "Escritura",
    "slug": "writing"
  },
  "medical-recipes": {
    "title": "Lista de Recetas Médicas",
    "slug": "medical-recipes"
  },
  "monolith-ruleset": {
    "title": "Reglas de Monolith",
    "slug": "monolith-ruleset"
  },
  "monolith-rule-core-one-common-sense": {
    "title": "Regla Principal 1",
    "slug": "monolith-rule-core-one-common-sense"
  },
  "monolith-rule-core-two-respect": {
    "title": "Regla Principal 2",
    "slug": "monolith-rule-core-two-respect"
  },
  "monolith-rule-core-three-cheating-exploits": {
    "title": "Regla Principal 3",
    "slug": "monolith-rule-core-three-cheating-exploits"
  },
  "monolith-rule-core-four-alternative-accounts": {
    "title": "Regla Fundamental 4",
    "slug": "monolith-rule-core-four-alternative-accounts"
  },
  "monolith-rule-core-five-languages": {
    "title": "Regla Fundamental 5",
    "slug": "monolith-rule-core-five-languages"
  },
  "monolith-rule-core-six-ahelp": {
    "title": "Regla Principal 6.",
    "slug": "monolith-rule-core-six-ahelp"
  },
  "monolith-rule-core-seven-threaten-to-report": {
    "title": "Regla Principal 7.",
    "slug": "monolith-rule-core-seven-threaten-to-report"
  },
  "monolith-rule-roleplay-one-break-character": {
    "title": "Regla de Rol 1",
    "slug": "monolith-rule-roleplay-one-break-character"
  },
  "monolith-rule-roleplay-two-text-chat": {
    "title": "Regla de Roleplay 2",
    "slug": "monolith-rule-roleplay-two-text-chat"
  },
  "monolith-rule-roleplay-three-proper-grammar": {
    "title": "Regla de Roleplay 3",
    "slug": "monolith-rule-roleplay-three-proper-grammar"
  },
  "monolith-rule-roleplay-four-character-actions": {
    "title": "Regla de Rol 4",
    "slug": "monolith-rule-roleplay-four-character-actions"
  },
  "monolith-rule-roleplay-five-erotic-roleplay": {
    "title": "Regla de Rol 5",
    "slug": "monolith-rule-roleplay-five-erotic-roleplay"
  },
  "monolith-rule-roleplay-six-metagame": {
    "title": "Regla de Rol 6",
    "slug": "monolith-rule-roleplay-six-metagame"
  },
  "monolith-rule-roleplay-seven-safe-zones": {
    "title": "Regla de Rol 7",
    "slug": "monolith-rule-roleplay-seven-safe-zones"
  },
  "monolith-rule-roleplay-eight-faction-roles": {
    "title": "Regla de Rol 8",
    "slug": "monolith-rule-roleplay-eight-faction-roles"
  },
  "monolith-rule-roleplay-nine-commanding-roles": {
    "title": "Regla de Rol 9",
    "slug": "monolith-rule-roleplay-nine-commanding-roles"
  },
  "monolith-rule-conflict-one-random-deathmatch": {
    "title": "Regla de Conflicto 1",
    "slug": "monolith-rule-conflict-one-random-deathmatch"
  },
  "monolith-rule-conflict-two-new-life": {
    "title": "Regla de Conflicto 2",
    "slug": "monolith-rule-conflict-two-new-life"
  },
  "monolith-rule-conflict-three-fair-play": {
    "title": "Regla de Conflicto 3",
    "slug": "monolith-rule-conflict-three-fair-play"
  },
  "monolith-rule-conflict-four-port-striking": {
    "title": "Regla de Conflicto 4",
    "slug": "monolith-rule-conflict-four-port-striking"
  }
};
