// AUTO-GENERATED by scripts/generate-departments.mjs — DO NOT EDIT
// Run: npm run generate-departments

import type { GeneratedDepartment } from "./department-types";

export const monolithGeneratedDepartments: GeneratedDepartment[] = [
  {
    "id": "Cargo",
    "name": "Logística",
    "description": "Completa recompensas, gana Spessos y solicita suministros útiles para la tripulación.",
    "color": "#A46106",
    "jobs": []
  },
  {
    "id": "Civilian",
    "name": "Civil",
    "description": "¡Únete a una tripulación y sal a vivir aventuras!",
    "color": "#9FED58",
    "jobs": [
      {
        "id": "Contractor",
        "name": "Espacial"
      },
      {
        "id": "Mercenary",
        "name": "Mercenario"
      },
      {
        "id": "Pilot",
        "name": "Piloto"
      },
      {
        "id": "Borg",
        "name": "Cyborg"
      }
    ]
  },
  {
    "id": "CentralCommand",
    "name": "Mando Central",
    "description": "Pon el sector bajo control, mantén al Mando alerta.",
    "color": "#0c344d",
    "jobs": [
      {
        "id": "CentralCommandOfficial",
        "name": "Oficial de CentComm"
      },
      {
        "id": "ERTLeader",
        "name": "Líder del ERT"
      },
      {
        "id": "ERTChaplain",
        "name": "Capellán del ERT"
      },
      {
        "id": "ERTJanitor",
        "name": "Conserje del ERT"
      },
      {
        "id": "ERTMedical",
        "name": "Médico del ERT"
      },
      {
        "id": "ERTSecurity",
        "name": "Seguridad del ERT"
      },
      {
        "id": "ERTEngineer",
        "name": "Ingeniero del ERT"
      },
      {
        "id": "ERTMailCarrier",
        "name": "Mensajero ERT"
      }
    ]
  },
  {
    "id": "Command",
    "name": "Mando Central",
    "description": "Gestiona el sector, mantén todo funcionando de manera eficiente.",
    "color": "#334E6D",
    "jobs": [
      {
        "id": "StationRepresentative",
        "name": "Supervisor"
      },
      {
        "id": "Sheriff",
        "name": "Coronel de la TSFMC"
      },
      {
        "id": "StationTrafficController",
        "name": "Controlador de Tráfico Espacial"
      },
      {
        "id": "DirectorOfCare",
        "name": "Director de Atención"
      }
    ]
  },
  {
    "id": "Engineering",
    "name": "Ingeniería",
    "description": "Mantén la energía encendida y la estación operativa.",
    "color": "#EFB341",
    "jobs": []
  },
  {
    "id": "Medical",
    "name": "Despacho Médico",
    "description": "Respondedores médicos de emergencia, desplegados por el espacio para ayuda y rescate rápidos.",
    "color": "#52B4E9",
    "jobs": [
      {
        "id": "DirectorOfCare",
        "name": "Director de Atención"
      },
      {
        "id": "MdMedic",
        "name": "Respondedor de Emergencias"
      }
    ]
  },
  {
    "id": "Security",
    "name": "Destacamento del Cuerpo de Marines de la TSF",
    "description": "Mantén la paz en el sector.",
    "color": "#326DA8",
    "jobs": [
      {
        "id": "PrisonGuard",
        "name": "Guardia de Prisión"
      },
      {
        "id": "Brigmedic",
        "name": "Sanitario de la TSFMC"
      },
      {
        "id": "NFDetective",
        "name": "Detective"
      },
      {
        "id": "Cadet",
        "name": "Recluta de la TSFMC"
      },
      {
        "id": "Deputy",
        "name": "Marine de la TSFMC"
      },
      {
        "id": "Bailiff",
        "name": "Capitán de la TSFMC"
      },
      {
        "id": "Sheriff",
        "name": "Coronel de la TSFMC"
      },
      {
        "id": "SeniorOfficer",
        "name": "Líder de Equipo de la TSFMC"
      },
      {
        "id": "PublicAffairsLiaison",
        "name": "Enlace de Asuntos Públicos"
      },
      {
        "id": "TsfEngineer",
        "name": "Ingeniero TSFMC"
      },
      {
        "id": "TsfMarsoc",
        "name": "Operativo MARSOC de la TSFMC"
      },
      {
        "id": "TsfBorg",
        "name": "Cyborg TSFMC"
      }
    ]
  },
  {
    "id": "Science",
    "name": "Ciencia",
    "description": "Investiga artefactos y anomalías para inventar nuevos equipos para la estación",
    "color": "#D381C9",
    "jobs": []
  },
  {
    "id": "Silicon",
    "name": "Silicio",
    "description": "Obedece tus leyes y sirve a la tripulación.",
    "color": "#D381C9",
    "jobs": [
      {
        "id": "Borg",
        "name": "Cyborg"
      },
      {
        "id": "StationAi",
        "name": "IA de Estación"
      }
    ]
  },
  {
    "id": "Specific",
    "name": "Específico de estación",
    "description": "Trabajos que no todas las estaciones tienen.",
    "color": "#9FED58",
    "jobs": []
  },
  {
    "id": "Frontier",
    "name": "Colonización Frontier de Colossus",
    "description": "Haz tu parte para expandir la influencia de la TSF en el sector.",
    "color": "#334E6D",
    "jobs": [
      {
        "id": "StationRepresentative",
        "name": "Supervisor"
      },
      {
        "id": "StationTrafficController",
        "name": "Controlador de Tráfico Espacial"
      },
      {
        "id": "CCServiceWorker",
        "name": "Trabajador de Servicio"
      },
      {
        "id": "NFJanitor",
        "name": "Conserje"
      },
      {
        "id": "MailCarrier",
        "name": "Cartero"
      },
      {
        "id": "SecurityGuard",
        "name": "Juez"
      }
    ]
  },
  {
    "id": "Antag",
    "name": "Phaethon Dynasty Imperial Vanguard",
    "description": "Socava los esfuerzos de la Trans-Solar Federation en el sector y sé una molestia para la sociedad en general.",
    "color": "#DE3A3A",
    "jobs": [
      {
        "id": "PirateCaptain",
        "name": "PDV Gran Visir"
      },
      {
        "id": "PirateFirstMate",
        "name": "PDV Asvaran"
      },
      {
        "id": "PDVDenasvar",
        "name": "PDV Denasvar"
      },
      {
        "id": "Pirate",
        "name": "PDV Rahkshan"
      },
      {
        "id": "PDVInfiltrator",
        "name": "PDV Spasaka"
      },
      {
        "id": "PdvBorg",
        "name": "Cyborg PDV"
      },
      {
        "id": "PDVTarkhan",
        "name": "Tarkhan de la PDV"
      },
      {
        "id": "Prisoner",
        "name": "Prisionero"
      }
    ]
  },
  {
    "id": "PMC",
    "name": "Contratistas Militares Privados",
    "description": "Contratistas enfocados en el combate, con menos restricciones en el equipo que pueden llevar.",
    "color": "#7D8A3F",
    "jobs": [
      {
        "id": "Mercenary",
        "name": "Mercenario"
      }
    ]
  },
  {
    "id": "UnionOfSovietSocialistPlanets",
    "name": "Unión de Planetas Socialistas Soviéticos",
    "description": "Sirve a la gloriosa Unión en el espacio contra las fuerzas de TSFMC y PDV.",
    "color": "#b2224b",
    "jobs": [
      {
        "id": "USSPCommissar",
        "name": "Comisario USSP"
      },
      {
        "id": "USSPSergeant",
        "name": "USSP Serzhant"
      },
      {
        "id": "USSPRifleman",
        "name": "Fusilero USSP"
      }
    ]
  },
  {
    "id": "ViperGroup",
    "name": "Viper Group",
    "description": "Contratistas de élite pertenecientes a una empresa de orígenes sindicales.",
    "color": "#6b0000",
    "jobs": [
      {
        "id": "VGInfanteer",
        "name": "Infantero VG"
      },
      {
        "id": "VGLieutenant",
        "name": "Teniente VG"
      },
      {
        "id": "VGCommander",
        "name": "Comandante VG"
      }
    ]
  }
];
