// AUTO-GENERATED by scripts/generate-guides.mjs — DO NOT EDIT
// Lightweight lookup maps for client components (no guide content)
// Run: npm run generate-guides

import type { GuideMeta } from "./guide-types";

export const scpGuideIdToSlug: Record<string, string> = {
  "NewPlayer": "new-player",
  "Controls": "controls",
  "Radio": "radio",
  "CharacterCreation": "character-creation",
  "YourFirstCharacter": "your-first-character",
  "Species": "species",
  "Arachnid": "arachnid",
  "Demon": "demon",
  "Diona": "diona",
  "Dwarf": "dwarf",
  "Felinid": "felinid",
  "Human": "human",
  "HumanoidXeno": "humanoid-xeno",
  "Milira": "milira",
  "Moth": "moth",
  "Predator": "predator",
  "Reptilian": "reptilian",
  "Resomi": "resomi",
  "SlimePerson": "slime-person",
  "Swine": "swine",
  "Tajaran": "tajaran",
  "Vox": "vox",
  "Vulpkanin": "vulpkanin",
  "SS14": "ss14",
  "Jobs": "jobs",
  "Service": "service",
  "Bartender": "bartender",
  "Botany": "botany",
  "Chef": "chef",
  "Janitorial": "janitorial",
  "Cargo": "cargo",
  "CargoBounties": "cargo-bounties",
  "Salvage": "salvage",
  "Medical": "medical",
  "MedicalDoctor": "medical-doctor",
  "Chemist": "chemist",
  "Botanicals": "botanicals",
  "AdvancedBrute": "advanced-brute",
  "Cloning": "cloning",
  "Cryogenics": "cryogenics",
  "Science": "science",
  "Technologies": "technologies",
  "AnomalousResearch": "anomalous-research",
  "APE": "ape",
  "ScannersAndVessels": "scanners-and-vessels",
  "Xenoarchaeology": "xenoarchaeology",
  "AnalysisConsole": "analysis-console",
  "XenoarchaeologyUnlockingNodes": "xenoarchaeology-unlocking-nodes",
  "Robotics": "robotics",
  "Cyborgs": "cyborgs",
  "Engineering": "engineering",
  "Construction": "construction",
  "Airlocks": "airlocks",
  "AirlockSecurity": "airlock-security",
  "ExpandingRepairingStation": "expanding-repairing-station",
  "WirePanels": "wire-panels",
  "Power": "power",
  "Generators": "generators",
  "PortableGenerator": "portable-generator",
  "AME": "ame",
  "SingularityTeslaEngine": "singularity-tesla-engine",
  "SingularityEngine": "singularity-engine",
  "TeslaEngine": "tesla-engine",
  "TEG": "teg",
  "RTG": "rtg",
  "SolarPanels": "solar-panels",
  "InspectingPower": "inspecting-power",
  "PowerStorage": "power-storage",
  "Ramping": "ramping",
  "VoltageNetworks": "voltage-networks",
  "Atmospherics": "atmospherics",
  "GasManipulation": "gas-manipulation",
  "AtmosphereInOut": "atmosphere-in-out",
  "AirVent": "air-vent",
  "PassiveVent": "passive-vent",
  "AirInjector": "air-injector",
  "AirScrubber": "air-scrubber",
  "PortableScrubber": "portable-scrubber",
  "Pipes": "pipes",
  "Pumps": "pumps",
  "Valves": "valves",
  "ManualValve": "manual-valve",
  "SignalValve": "signal-valve",
  "PneumaticValve": "pneumatic-valve",
  "PassiveGate": "passive-gate",
  "PressureRegulator": "pressure-regulator",
  "MixingAndFiltering": "mixing-and-filtering",
  "GasCanisters": "gas-canisters",
  "Thermomachines": "thermomachines",
  "Radiators": "radiators",
  "GasCondensing": "gas-condensing",
  "GasRecycling": "gas-recycling",
  "AtmosphericsSystems": "atmospherics-systems",
  "PipeNetworks": "pipe-networks",
  "DeviceMonitoringAndControl": "device-monitoring-and-control",
  "AirAlarms": "air-alarms",
  "AtmosphericAlertsComputer": "atmospheric-alerts-computer",
  "AtmosphericNetworkMonitor": "atmospheric-network-monitor",
  "FireAndGasControl": "fire-and-gas-control",
  "GasMiningAndStorage": "gas-mining-and-storage",
  "AtmosphericUpsets": "atmospheric-upsets",
  "Fires": "fires",
  "Spacing": "spacing",
  "DeltaPressure": "delta-pressure",
  "AtmosTools": "atmos-tools",
  "Gasses": "gasses",
  "ShuttleCraft": "shuttle-craft",
  "Networking": "networking",
  "AccessConfigurator": "access-configurator",
  "Security": "security",
  "Forensics": "forensics",
  "Defusal": "defusal",
  "CriminalRecords": "criminal-records",
  "SpaceLaw": "space-law",
  "SpaceLawCrimeList": "space-law-crime-list",
  "Command": "command",
  "Survival": "survival",
  "Antagonists": "antagonists",
  "Traitors": "traitors",
  "Thieves": "thieves",
  "Revolutionaries": "revolutionaries",
  "NuclearOperatives": "nuclear-operatives",
  "SpaceNinja": "space-ninja",
  "Wizard": "wizard",
  "Zombies": "zombies",
  "Xenoborgs": "xenoborgs",
  "MinorAntagonists": "minor-antagonists",
  "Changelings": "changelings",
  "FleshCult": "flesh-cult",
  "SELFAgent": "self-agent",
  "Glossary": "glossary",
  "ScpResearch": "scp-research",
  "ScpResearchAdvanced": "scp-research-advanced",
  "ScpGlossary": "scp-glossary",
  "ScpBasicTerms": "scp-basic-terms",
  "ScpResearchableEquipment": "scp-researchable-equipment",
  "ScpAbbreviations": "scp-abbreviations",
  "ScpFear": "scp-fear",
  "Scp173About": "scp173about",
  "Scp173Abilities": "scp173abilities",
  "Scp173Containment": "scp173containment",
  "Scp173ContainmentBreach": "scp173containment-breach",
  "Scp096About": "scp096about",
  "Scp096States": "scp096states",
  "Scp096Abilities": "scp096abilities",
  "Scp096Containment": "scp096containment",
  "Scp096ContainmentBreach": "scp096containment-breach",
  "Scp082About": "scp082about",
  "Scp082Abilities": "scp082abilities",
  "Scp082Containment": "scp082containment",
  "Scp082ContainmentBreach": "scp082containment-breach",
  "Scp106About": "scp106about",
  "Scp106Abilities": "scp106abilities",
  "Scp106Containment": "scp106containment",
  "Scp106ContainmentBreach": "scp106containment-breach",
  "Scp457About": "scp457about",
  "Scp457States": "scp457states",
  "Scp457Abilities": "scp457abilities",
  "Scp457Containment": "scp457containment",
  "Scp457ContainmentBreach": "scp457containment-breach",
  "Expeditions": "expeditions",
  "MobsExpeditionGuidePirates": "mobs-expedition-guide-pirates",
  "MobsExpeditionGuideSoviets": "mobs-expedition-guide-soviets",
  "MobsExpeditionGuideSilicons": "mobs-expedition-guide-silicons",
  "MobsExpeditionGuideXenos": "mobs-expedition-guide-xenos",
  "MobsExpeditionGuideCarps": "mobs-expedition-guide-carps",
  "FireStationRuleset": "fire-station-ruleset",
  "References": "references",
  "Chemicals": "chemicals",
  "Elements": "elements",
  "Medicine": "medicine",
  "Narcotics": "narcotics",
  "Pyrotechnic": "pyrotechnic",
  "Toxins": "toxins",
  "Foods": "foods",
  "Botanical": "botanical",
  "Biological": "biological",
  "Special": "special",
  "Others": "others",
  "Drinks": "drinks",
  "FoodRecipes": "food-recipes",
  "PizzaRecipes": "pizza-recipes",
  "SavoryRecipes": "savory-recipes",
  "BreadRecipes": "bread-recipes",
  "BreakfastRecipes": "breakfast-recipes",
  "MothRecipes": "moth-recipes",
  "PastaRecipes": "pasta-recipes",
  "DessertRecipes": "dessert-recipes",
  "SoupRecipes": "soup-recipes",
  "PieRecipes": "pie-recipes",
  "BarsAndCookiesRecipes": "bars-and-cookies-recipes",
  "CakeRecipes": "cake-recipes",
  "SaladRecipes": "salad-recipes",
  "OtherRecipes": "other-recipes",
  "MedicinalRecipes": "medicinal-recipes",
  "SecretRecipes": "secret-recipes",
  "Writing": "writing",
  "Lawsets": "lawsets"
};

export const scpGuideSlugsToMeta: Record<string, GuideMeta> = {
  "new-player": {
    "title": "Primeros pasos",
    "slug": "new-player"
  },
  "controls": {
    "title": "Controles",
    "slug": "controls"
  },
  "radio": {
    "title": "Habla y canales de texto",
    "slug": "radio"
  },
  "character-creation": {
    "title": "Consejos importantes para crear un personaje",
    "slug": "character-creation"
  },
  "your-first-character": {
    "title": "Capitanes y payasos",
    "slug": "your-first-character"
  },
  "species": {
    "title": "Especies",
    "slug": "species"
  },
  "arachnid": {
    "title": "Arácnidos",
    "slug": "arachnid"
  },
  "demon": {
    "title": "Arcanos",
    "slug": "demon"
  },
  "diona": {
    "title": "Diona",
    "slug": "diona"
  },
  "dwarf": {
    "title": "Enanos",
    "slug": "dwarf"
  },
  "felinid": {
    "title": "Felínidos",
    "slug": "felinid"
  },
  "human": {
    "title": "Humanos",
    "slug": "human"
  },
  "humanoid-xeno": {
    "title": "Xenomorfos humanoides",
    "slug": "humanoid-xeno"
  },
  "milira": {
    "title": "Milira",
    "slug": "milira"
  },
  "moth": {
    "title": "Personas polilla",
    "slug": "moth"
  },
  "predator": {
    "title": "Yautja",
    "slug": "predator"
  },
  "reptilian": {
    "title": "Reptilianos",
    "slug": "reptilian"
  },
  "resomi": {
    "title": "Resomi",
    "slug": "resomi"
  },
  "slime-person": {
    "title": "Personas slime",
    "slug": "slime-person"
  },
  "swine": {
    "title": "Trottins",
    "slug": "swine"
  },
  "tajaran": {
    "title": "Tajaras",
    "slug": "tajaran"
  },
  "vox": {
    "title": "Vox",
    "slug": "vox"
  },
  "vulpkanin": {
    "title": "Vulpkanin",
    "slug": "vulpkanin"
  },
  "ss14": {
    "title": "Space Station 14",
    "slug": "ss14"
  },
  "jobs": {
    "title": "Trabajos",
    "slug": "jobs"
  },
  "service": {
    "title": "Servicio",
    "slug": "service"
  },
  "bartender": {
    "title": "Camarero",
    "slug": "bartender"
  },
  "botany": {
    "title": "Botánica",
    "slug": "botany"
  },
  "chef": {
    "title": "Cocinero",
    "slug": "chef"
  },
  "janitorial": {
    "title": "Limpieza",
    "slug": "janitorial"
  },
  "cargo": {
    "title": "Carga",
    "slug": "cargo"
  },
  "cargo-bounties": {
    "title": "Recompensas de Carga",
    "slug": "cargo-bounties"
  },
  "salvage": {
    "title": "Salvamento",
    "slug": "salvage"
  },
  "medical": {
    "title": "Medicina",
    "slug": "medical"
  },
  "medical-doctor": {
    "title": "Médico",
    "slug": "medical-doctor"
  },
  "chemist": {
    "title": "Químico",
    "slug": "chemist"
  },
  "botanicals": {
    "title": "Productos botánicos",
    "slug": "botanicals"
  },
  "advanced-brute": {
    "title": "Medicamentos especializados contra lesiones físicas",
    "slug": "advanced-brute"
  },
  "cloning": {
    "title": "Clonación",
    "slug": "cloning"
  },
  "cryogenics": {
    "title": "Criogenia",
    "slug": "cryogenics"
  },
  "science": {
    "title": "Ciencia",
    "slug": "science"
  },
  "technologies": {
    "title": "Tecnologías",
    "slug": "technologies"
  },
  "anomalous-research": {
    "title": "Investigación de anomalías",
    "slug": "anomalous-research"
  },
  "ape": {
    "title": "E.P.A.",
    "slug": "ape"
  },
  "scanners-and-vessels": {
    "title": "Escáner de anomalías",
    "slug": "scanners-and-vessels"
  },
  "xenoarchaeology": {
    "title": "Xenoarqueología",
    "slug": "xenoarchaeology"
  },
  "analysis-console": {
    "title": "Consola de análisis",
    "slug": "analysis-console"
  },
  "xenoarchaeology-unlocking-nodes": {
    "title": "Desbloqueo de nodos",
    "slug": "xenoarchaeology-unlocking-nodes"
  },
  "robotics": {
    "title": "Robótica",
    "slug": "robotics"
  },
  "cyborgs": {
    "title": "Cíborgs",
    "slug": "cyborgs"
  },
  "engineering": {
    "title": "Ingeniería",
    "slug": "engineering"
  },
  "construction": {
    "title": "Construcción",
    "slug": "construction"
  },
  "airlocks": {
    "title": "Esclusas",
    "slug": "airlocks"
  },
  "airlock-security": {
    "title": "Mejoras de las esclusas",
    "slug": "airlock-security"
  },
  "expanding-repairing-station": {
    "title": "Ampliación y reparación de estaciones",
    "slug": "expanding-repairing-station"
  },
  "wire-panels": {
    "title": "Paneles de cableado",
    "slug": "wire-panels"
  },
  "power": {
    "title": "Energía",
    "slug": "power"
  },
  "generators": {
    "title": "Generadores",
    "slug": "generators"
  },
  "portable-generator": {
    "title": "Generadores portátiles",
    "slug": "portable-generator"
  },
  "ame": {
    "title": "Motor de antimateria (AME)",
    "slug": "ame"
  },
  "singularity-tesla-engine": {
    "title": "Motor de singularidad / motor Tesla",
    "slug": "singularity-tesla-engine"
  },
  "singularity-engine": {
    "title": "Motor de singularidad",
    "slug": "singularity-engine"
  },
  "tesla-engine": {
    "title": "Motor Tesla",
    "slug": "tesla-engine"
  },
  "teg": {
    "title": "Motor termoeléctrico (TEG)",
    "slug": "teg"
  },
  "rtg": {
    "title": "Generador termoeléctrico de radioisótopos (RTG)",
    "slug": "rtg"
  },
  "solar-panels": {
    "title": "Paneles solares",
    "slug": "solar-panels"
  },
  "inspecting-power": {
    "title": "Inspección de la red eléctrica",
    "slug": "inspecting-power"
  },
  "power-storage": {
    "title": "Almacenamiento de energía",
    "slug": "power-storage"
  },
  "ramping": {
    "title": "Aumento gradual de potencia",
    "slug": "ramping"
  },
  "voltage-networks": {
    "title": "Redes de tensión",
    "slug": "voltage-networks"
  },
  "atmospherics": {
    "title": "Atmosféricos",
    "slug": "atmospherics"
  },
  "gas-manipulation": {
    "title": "Manipulación de gases",
    "slug": "gas-manipulation"
  },
  "atmosphere-in-out": {
    "title": "Entrada y salida de atmósfera",
    "slug": "atmosphere-in-out"
  },
  "air-vent": {
    "title": "Respiradero",
    "slug": "air-vent"
  },
  "passive-vent": {
    "title": "Respiradero pasivo",
    "slug": "passive-vent"
  },
  "air-injector": {
    "title": "Inyector de aire",
    "slug": "air-injector"
  },
  "air-scrubber": {
    "title": "Depurador atmosférico",
    "slug": "air-scrubber"
  },
  "portable-scrubber": {
    "title": "Depurador portátil",
    "slug": "portable-scrubber"
  },
  "pipes": {
    "title": "Tuberías",
    "slug": "pipes"
  },
  "pumps": {
    "title": "Bombas",
    "slug": "pumps"
  },
  "valves": {
    "title": "Válvulas",
    "slug": "valves"
  },
  "manual-valve": {
    "title": "Válvula manual",
    "slug": "manual-valve"
  },
  "signal-valve": {
    "title": "Válvula de señal",
    "slug": "signal-valve"
  },
  "pneumatic-valve": {
    "title": "Válvula neumática",
    "slug": "pneumatic-valve"
  },
  "passive-gate": {
    "title": "Válvula pasiva",
    "slug": "passive-gate"
  },
  "pressure-regulator": {
    "title": "Regulador de presión de entrada",
    "slug": "pressure-regulator"
  },
  "mixing-and-filtering": {
    "title": "Mezcla y filtrado",
    "slug": "mixing-and-filtering"
  },
  "gas-canisters": {
    "title": "Contenedores de gas",
    "slug": "gas-canisters"
  },
  "thermomachines": {
    "title": "Termomáquinas",
    "slug": "thermomachines"
  },
  "radiators": {
    "title": "Radiadores",
    "slug": "radiators"
  },
  "gas-condensing": {
    "title": "Condensación de gases",
    "slug": "gas-condensing"
  },
  "gas-recycling": {
    "title": "Reciclaje de gases",
    "slug": "gas-recycling"
  },
  "atmospherics-systems": {
    "title": "Sistemas atmosféricos",
    "slug": "atmospherics-systems"
  },
  "pipe-networks": {
    "title": "Redes de tuberías",
    "slug": "pipe-networks"
  },
  "device-monitoring-and-control": {
    "title": "Supervisión y control de dispositivos",
    "slug": "device-monitoring-and-control"
  },
  "air-alarms": {
    "title": "Alarmas atmosféricas",
    "slug": "air-alarms"
  },
  "atmospheric-alerts-computer": {
    "title": "Computadora de alertas atmosféricas",
    "slug": "atmospheric-alerts-computer"
  },
  "atmospheric-network-monitor": {
    "title": "Monitor de redes atmosféricas",
    "slug": "atmospheric-network-monitor"
  },
  "fire-and-gas-control": {
    "title": "Control de incendios y gases",
    "slug": "fire-and-gas-control"
  },
  "gas-mining-and-storage": {
    "title": "Extracción y almacenamiento de gases",
    "slug": "gas-mining-and-storage"
  },
  "atmospheric-upsets": {
    "title": "Incidentes atmosféricos",
    "slug": "atmospheric-upsets"
  },
  "fires": {
    "title": "Incendios",
    "slug": "fires"
  },
  "spacing": {
    "title": "Despresurización",
    "slug": "spacing"
  },
  "delta-pressure": {
    "title": "Diferencia de presión",
    "slug": "delta-pressure"
  },
  "atmos-tools": {
    "title": "Herramientas de Atmosféricos",
    "slug": "atmos-tools"
  },
  "gasses": {
    "title": "Gases",
    "slug": "gasses"
  },
  "shuttle-craft": {
    "title": "Nave lanzadera",
    "slug": "shuttle-craft"
  },
  "networking": {
    "title": "Redes de dispositivos",
    "slug": "networking"
  },
  "access-configurator": {
    "title": "Configurador de accesos",
    "slug": "access-configurator"
  },
  "security": {
    "title": "Seguridad",
    "slug": "security"
  },
  "forensics": {
    "title": "Investigación forense",
    "slug": "forensics"
  },
  "defusal": {
    "title": "Desactivación de bombas grandes",
    "slug": "defusal"
  },
  "criminal-records": {
    "title": "Antecedentes penales",
    "slug": "criminal-records"
  },
  "space-law": {
    "title": "Derecho espacial",
    "slug": "space-law"
  },
  "space-law-crime-list": {
    "title": "Derecho espacial: lista de delitos",
    "slug": "space-law-crime-list"
  },
  "command": {
    "title": "Mando",
    "slug": "command"
  },
  "survival": {
    "title": "Supervivencia",
    "slug": "survival"
  },
  "antagonists": {
    "title": "Antagonistas",
    "slug": "antagonists"
  },
  "traitors": {
    "title": "Traidores",
    "slug": "traitors"
  },
  "thieves": {
    "title": "Ladrones",
    "slug": "thieves"
  },
  "revolutionaries": {
    "title": "Revolucionarios",
    "slug": "revolutionaries"
  },
  "nuclear-operatives": {
    "title": "Operativos nucleares",
    "slug": "nuclear-operatives"
  },
  "space-ninja": {
    "title": "Ninja espacial",
    "slug": "space-ninja"
  },
  "wizard": {
    "title": "Mago",
    "slug": "wizard"
  },
  "zombies": {
    "title": "Zombis",
    "slug": "zombies"
  },
  "xenoborgs": {
    "title": "Xenocíborgs",
    "slug": "xenoborgs"
  },
  "minor-antagonists": {
    "title": "Antagonistas menores",
    "slug": "minor-antagonists"
  },
  "changelings": {
    "title": "Cambiaformas",
    "slug": "changelings"
  },
  "flesh-cult": {
    "title": "Cultista de la carne",
    "slug": "flesh-cult"
  },
  "self-agent": {
    "title": "Frente de Liberación de Silicios",
    "slug": "self-agent"
  },
  "glossary": {
    "title": "Glosario",
    "slug": "glossary"
  },
  "scp-research": {
    "title": "Investigación de la Fundación",
    "slug": "scp-research"
  },
  "scp-research-advanced": {
    "title": "Material de investigación",
    "slug": "scp-research-advanced"
  },
  "scp-glossary": {
    "title": "Glosario SCP",
    "slug": "scp-glossary"
  },
  "scp-basic-terms": {
    "title": "Términos básicos",
    "slug": "scp-basic-terms"
  },
  "scp-researchable-equipment": {
    "title": "Equipo disponible mediante investigación",
    "slug": "scp-researchable-equipment"
  },
  "scp-abbreviations": {
    "title": "Abreviaturas de departamentos y servicios",
    "slug": "scp-abbreviations"
  },
  "scp-fear": {
    "title": "Sistema de miedo",
    "slug": "scp-fear"
  },
  "scp173about": {
    "title": "SCP-173 «La Escultura»",
    "slug": "scp173about"
  },
  "scp173abilities": {
    "title": "Capacidades de SCP-173",
    "slug": "scp173abilities"
  },
  "scp173containment": {
    "title": "Contención de SCP-173",
    "slug": "scp173containment"
  },
  "scp173containment-breach": {
    "title": "¿Cómo escapar?",
    "slug": "scp173containment-breach"
  },
  "scp096about": {
    "title": "SCP-096 «El Chico Tímido»",
    "slug": "scp096about"
  },
  "scp096states": {
    "title": "Estados",
    "slug": "scp096states"
  },
  "scp096abilities": {
    "title": "Habilidades de SCP-096",
    "slug": "scp096abilities"
  },
  "scp096containment": {
    "title": "Contención de SCP-096",
    "slug": "scp096containment"
  },
  "scp096containment-breach": {
    "title": "¿Cómo escapar?",
    "slug": "scp096containment-breach"
  },
  "scp082about": {
    "title": "SCP-082 «Fernand el Caníbal»",
    "slug": "scp082about"
  },
  "scp082abilities": {
    "title": "Capacidades de SCP-082",
    "slug": "scp082abilities"
  },
  "scp082containment": {
    "title": "Contención de SCP-082",
    "slug": "scp082containment"
  },
  "scp082containment-breach": {
    "title": "¿Cómo escapar?",
    "slug": "scp082containment-breach"
  },
  "scp106about": {
    "title": "SCP-106 «El Viejo»",
    "slug": "scp106about"
  },
  "scp106abilities": {
    "title": "Capacidades de SCP-106",
    "slug": "scp106abilities"
  },
  "scp106containment": {
    "title": "Contención de SCP-106",
    "slug": "scp106containment"
  },
  "scp106containment-breach": {
    "title": "¿Cómo escapar?",
    "slug": "scp106containment-breach"
  },
  "scp457about": {
    "title": "SCP-457 «El Hombre Ardiente»",
    "slug": "scp457about"
  },
  "scp457states": {
    "title": "Estados",
    "slug": "scp457states"
  },
  "scp457abilities": {
    "title": "Capacidades de SCP-457",
    "slug": "scp457abilities"
  },
  "scp457containment": {
    "title": "Contención de SCP-457",
    "slug": "scp457containment"
  },
  "scp457containment-breach": {
    "title": "¿Cómo escapar?",
    "slug": "scp457containment-breach"
  },
  "expeditions": {
    "title": "Expediciones",
    "slug": "expeditions"
  },
  "mobs-expedition-guide-pirates": {
    "title": "Piratas",
    "slug": "mobs-expedition-guide-pirates"
  },
  "mobs-expedition-guide-soviets": {
    "title": "Comunistas",
    "slug": "mobs-expedition-guide-soviets"
  },
  "mobs-expedition-guide-silicons": {
    "title": "Silicios renegados",
    "slug": "mobs-expedition-guide-silicons"
  },
  "mobs-expedition-guide-xenos": {
    "title": "Xenos",
    "slug": "mobs-expedition-guide-xenos"
  },
  "mobs-expedition-guide-carps": {
    "title": "Carpas",
    "slug": "mobs-expedition-guide-carps"
  },
  "fire-station-ruleset": {
    "title": "Reglas del servidor",
    "slug": "fire-station-ruleset"
  },
  "references": {
    "title": "Referencias",
    "slug": "references"
  },
  "chemicals": {
    "title": "Sustancias químicas",
    "slug": "chemicals"
  },
  "elements": {
    "title": "Elementos",
    "slug": "elements"
  },
  "medicine": {
    "title": "Medicamentos esenciales",
    "slug": "medicine"
  },
  "narcotics": {
    "title": "Narcóticos",
    "slug": "narcotics"
  },
  "pyrotechnic": {
    "title": "Pirotecnia",
    "slug": "pyrotechnic"
  },
  "toxins": {
    "title": "Toxinas",
    "slug": "toxins"
  },
  "foods": {
    "title": "Alimentos",
    "slug": "foods"
  },
  "botanical": {
    "title": "Productos botánicos",
    "slug": "botanical"
  },
  "biological": {
    "title": "Biológicos",
    "slug": "biological"
  },
  "special": {
    "title": "Especiales",
    "slug": "special"
  },
  "others": {
    "title": "Otros",
    "slug": "others"
  },
  "drinks": {
    "title": "Bebidas",
    "slug": "drinks"
  },
  "food-recipes": {
    "title": "Recetas para microondas",
    "slug": "food-recipes"
  },
  "pizza-recipes": {
    "title": "Pizzas",
    "slug": "pizza-recipes"
  },
  "savory-recipes": {
    "title": "Recetas saladas",
    "slug": "savory-recipes"
  },
  "bread-recipes": {
    "title": "Panes",
    "slug": "bread-recipes"
  },
  "breakfast-recipes": {
    "title": "Recetas de desayuno",
    "slug": "breakfast-recipes"
  },
  "moth-recipes": {
    "title": "Comida para polillas",
    "slug": "moth-recipes"
  },
  "pasta-recipes": {
    "title": "Pastas y fideos",
    "slug": "pasta-recipes"
  },
  "dessert-recipes": {
    "title": "Repostería & postres",
    "slug": "dessert-recipes"
  },
  "soup-recipes": {
    "title": "Sopas & guisos",
    "slug": "soup-recipes"
  },
  "pie-recipes": {
    "title": "Tartas & barritas",
    "slug": "pie-recipes"
  },
  "bars-and-cookies-recipes": {
    "title": "Barritas y galletas",
    "slug": "bars-and-cookies-recipes"
  },
  "cake-recipes": {
    "title": "Tartas",
    "slug": "cake-recipes"
  },
  "salad-recipes": {
    "title": "Ensaladas",
    "slug": "salad-recipes"
  },
  "other-recipes": {
    "title": "Otras recetas",
    "slug": "other-recipes"
  },
  "medicinal-recipes": {
    "title": "Recetas medicinales",
    "slug": "medicinal-recipes"
  },
  "secret-recipes": {
    "title": "Recetas secretas",
    "slug": "secret-recipes"
  },
  "writing": {
    "title": "Escritura",
    "slug": "writing"
  },
  "lawsets": {
    "title": "Conjuntos de leyes habituales para sintéticos",
    "slug": "lawsets"
  }
};
