// AUTO-GENERATED by scripts/generate-departments.mjs — DO NOT EDIT
// Run: npm run generate-departments

import type { GeneratedDepartment } from "./department-types";

export const scpGeneratedDepartments: GeneratedDepartment[] = [
  {
    "id": "Cargo",
    "name": "department-Cargo",
    "description": "",
    "color": "#9E6A34",
    "jobs": [
      {
        "id": "CargoTechnician",
        "name": "técnico de carga"
      },
      {
        "id": "Quartermaster",
        "name": "intendente"
      },
      {
        "id": "SalvageSpecialist",
        "name": "especialista en recuperación"
      },
      {
        "id": "MailCarrier",
        "name": "cartero"
      },
      {
        "id": "MiningSpecialist",
        "name": "especialista en minería"
      }
    ]
  },
  {
    "id": "Civilian",
    "name": "department-Civilian",
    "description": "",
    "color": "#4e7c22",
    "jobs": [
      {
        "id": "Bartender",
        "name": "camarero"
      },
      {
        "id": "Botanist",
        "name": "botánico"
      },
      {
        "id": "Chaplain",
        "name": "capellán"
      },
      {
        "id": "Chef",
        "name": "chef"
      },
      {
        "id": "Clown",
        "name": "payaso"
      },
      {
        "id": "HeadOfPersonnel",
        "name": "jefe de personal"
      },
      {
        "id": "Janitor",
        "name": "limpiador"
      },
      {
        "id": "Librarian",
        "name": "bibliotecario"
      },
      {
        "id": "Mime",
        "name": "mimo"
      },
      {
        "id": "Musician",
        "name": "músico"
      },
      {
        "id": "Passenger",
        "name": "pasajero"
      },
      {
        "id": "Reporter",
        "name": "periodista"
      },
      {
        "id": "Visitor",
        "name": "visitante"
      },
      {
        "id": "ServiceWorker",
        "name": "trabajador de servicios"
      },
      {
        "id": "Barber",
        "name": "peluquero"
      },
      {
        "id": "ComMaid",
        "name": "asistente de limpieza del Mando"
      }
    ]
  },
  {
    "id": "Command",
    "name": "department-Command",
    "description": "",
    "color": "#065290",
    "jobs": [
      {
        "id": "Captain",
        "name": "capitán"
      },
      {
        "id": "ChiefEngineer",
        "name": "ingeniero jefe"
      },
      {
        "id": "ChiefMedicalOfficer",
        "name": "director médico"
      },
      {
        "id": "HeadOfPersonnel",
        "name": "jefe de personal"
      },
      {
        "id": "HeadOfSecurity",
        "name": "jefe de seguridad"
      },
      {
        "id": "ResearchDirector",
        "name": "director de investigación"
      },
      {
        "id": "Quartermaster",
        "name": "intendente"
      },
      {
        "id": "NanoTrasenRepresentative",
        "name": "representante de NanoTrasen"
      },
      {
        "id": "Adjutant",
        "name": "ayudante de mando"
      },
      {
        "id": "ComMaid",
        "name": "asistente de limpieza del Mando"
      }
    ]
  },
  {
    "id": "Engineering",
    "name": "department-Engineering",
    "description": "",
    "color": "#c07d1e",
    "jobs": [
      {
        "id": "AtmosphericTechnician",
        "name": "técnico atmosférico"
      },
      {
        "id": "ChiefEngineer",
        "name": "ingeniero jefe"
      },
      {
        "id": "SeniorEngineer",
        "name": "ingeniero sénior"
      },
      {
        "id": "StationEngineer",
        "name": "ingeniero de estación"
      },
      {
        "id": "TechnicalAssistant",
        "name": "ayudante técnico"
      }
    ]
  },
  {
    "id": "Medical",
    "name": "department-Medical",
    "description": "",
    "color": "#3b627a",
    "jobs": [
      {
        "id": "Chemist",
        "name": "químico"
      },
      {
        "id": "ChiefMedicalOfficer",
        "name": "director médico"
      },
      {
        "id": "SeniorPhysician",
        "name": "médico sénior"
      },
      {
        "id": "MedicalDoctor",
        "name": "médico"
      },
      {
        "id": "MedicalIntern",
        "name": "interno de medicina"
      },
      {
        "id": "Psychologist",
        "name": "psicólogo"
      },
      {
        "id": "Paramedic",
        "name": "paramédico"
      },
      {
        "id": "MedicalPathologist",
        "name": "patólogo"
      }
    ]
  },
  {
    "id": "Security",
    "name": "department-Security",
    "description": "",
    "color": "#770101",
    "jobs": [
      {
        "id": "HeadOfSecurity",
        "name": "jefe de seguridad"
      },
      {
        "id": "SeniorOfficer",
        "name": "instructor de seguridad"
      },
      {
        "id": "SecurityCadet",
        "name": "cadete de seguridad"
      },
      {
        "id": "SecurityOfficer",
        "name": "agente de seguridad"
      },
      {
        "id": "Detective",
        "name": "detective"
      },
      {
        "id": "Warden",
        "name": "alcaide"
      },
      {
        "id": "Brigmedic",
        "name": "médico de brigada"
      },
      {
        "id": "SecurityPilot",
        "name": "piloto de seguridad"
      }
    ]
  },
  {
    "id": "Science",
    "name": "department-Science",
    "description": "",
    "color": "#984EB4",
    "jobs": [
      {
        "id": "ResearchDirector",
        "name": "director de investigación"
      },
      {
        "id": "SeniorResearcher",
        "name": "investigador sénior"
      },
      {
        "id": "Scientist",
        "name": "científico"
      },
      {
        "id": "ResearchAssistant",
        "name": "ayudante de investigación"
      },
      {
        "id": "Roboticist",
        "name": "robotista"
      }
    ]
  },
  {
    "id": "Silicon",
    "name": "department-Silicon",
    "description": "",
    "color": "#61738d",
    "jobs": [
      {
        "id": "StationAi",
        "name": "IA de la estación"
      },
      {
        "id": "Borg",
        "name": "cíborg"
      },
      {
        "id": "MedicalBorg",
        "name": "cíborg médico"
      },
      {
        "id": "EngineerBorg",
        "name": "cíborg de ingeniería"
      },
      {
        "id": "MiningBorg",
        "name": "Mining Borg"
      },
      {
        "id": "JanitorBorg",
        "name": "cíborg de limpieza"
      },
      {
        "id": "ServiceBorg",
        "name": "cíborg de servicio"
      },
      {
        "id": "ClownBorg",
        "name": "cíborg payaso"
      },
      {
        "id": "PeaceBorg",
        "name": "cíborg pacificador"
      },
      {
        "id": "SecurityBorg",
        "name": "cíborg de seguridad"
      }
    ]
  },
  {
    "id": "Specific",
    "name": "department-Specific",
    "description": "",
    "color": "#7f7f7f",
    "jobs": [
      {
        "id": "Reporter",
        "name": "periodista"
      },
      {
        "id": "Psychologist",
        "name": "psicólogo"
      },
      {
        "id": "Barber",
        "name": "peluquero"
      }
    ]
  },
  {
    "id": "Law",
    "name": "Departamento Jurídico",
    "description": "Defiende el orden jurídico, juzga los delitos y exige responsabilidades a quienes infrinjan la ley.",
    "color": "#FF5297",
    "jobs": [
      {
        "id": "Magistrat",
        "name": "magistrado"
      },
      {
        "id": "IAA",
        "name": "agente de asuntos internos"
      },
      {
        "id": "Lawyer",
        "name": "abogado"
      },
      {
        "id": "NtrOfficer",
        "name": "oficial del NTR"
      }
    ]
  },
  {
    "id": "BlueShield",
    "name": "Escudo Azul",
    "description": "Protege al personal de mando frente a cualquier intento de asesinato.",
    "color": "#0f4e81",
    "jobs": [
      {
        "id": "BlueShieldEnsign",
        "name": "comandante de Escudo Azul"
      },
      {
        "id": "BlueShieldOfficer",
        "name": "oficial de Escudo Azul"
      },
      {
        "id": "BlueShieldOperative",
        "name": "agente de Escudo Azul"
      }
    ]
  },
  {
    "id": "PlanetPrison",
    "name": "Prisión planetaria",
    "description": "En este lugar se difumina la frontera entre el control y la libertad, y sobrevivir depende de conservar el equilibrio.",
    "color": "#9f4000",
    "jobs": [
      {
        "id": "HeadOfPrison",
        "name": "alcaide"
      },
      {
        "id": "PrisonInspector",
        "name": "inspector penitenciario"
      },
      {
        "id": "PrisonWorker",
        "name": "operario penitenciario"
      },
      {
        "id": "PrisonEngineer",
        "name": "ingeniero de prisión"
      },
      {
        "id": "PrisonScientist",
        "name": "científico de prisión"
      },
      {
        "id": "PrisonDoctor",
        "name": "médico de prisión"
      },
      {
        "id": "PrisonChef",
        "name": "cocinero de prisión"
      },
      {
        "id": "PrisonTrainee",
        "name": "guardia de prisión en prácticas"
      },
      {
        "id": "PlanetPrisoner",
        "name": "preso de la prisión planetaria"
      }
    ]
  },
  {
    "id": "PlanetPrisonSecurity",
    "name": "Seguridad de la prisión planetaria",
    "description": "Impide las fugas y responde ante cualquier amenaza contra la seguridad de la prisión.",
    "color": "#691900",
    "jobs": [
      {
        "id": "HeadOfPrison",
        "name": "alcaide"
      },
      {
        "id": "PrisonInspector",
        "name": "inspector penitenciario"
      },
      {
        "id": "PrisonWorker",
        "name": "operario penitenciario"
      },
      {
        "id": "PrisonEngineer",
        "name": "ingeniero de prisión"
      },
      {
        "id": "PrisonScientist",
        "name": "científico de prisión"
      },
      {
        "id": "PrisonDoctor",
        "name": "médico de prisión"
      },
      {
        "id": "PrisonChef",
        "name": "cocinero de prisión"
      },
      {
        "id": "PrisonTrainee",
        "name": "guardia de prisión en prácticas"
      }
    ]
  },
  {
    "id": "CentralCommand",
    "name": "department-CentralCommand",
    "description": "",
    "color": "#0d4f1d",
    "jobs": [
      {
        "id": "CentCommOperator",
        "name": "operador del Mando Central"
      },
      {
        "id": "CentCommOfficial",
        "name": "representante del Mando Central"
      }
    ]
  },
  {
    "id": "SpecialOperations",
    "name": "Operaciones especiales",
    "description": "Lleva a cabo misiones secretas de alto riesgo para mantener la seguridad de la estación.",
    "color": "#0c344d",
    "jobs": [
      {
        "id": "CBURN",
        "name": "oficial de cuarentena del Mando Central"
      },
      {
        "id": "ERTLeader",
        "name": "líder del ERT"
      },
      {
        "id": "ERTChaplain",
        "name": "capellán del ERT"
      },
      {
        "id": "ERTJanitor",
        "name": "limpiador del ERT"
      },
      {
        "id": "ERTMedical",
        "name": "médico del ERT"
      },
      {
        "id": "ERTSecurity",
        "name": "agente de seguridad del ERT"
      },
      {
        "id": "ERTEngineer",
        "name": "ingeniero del ERT"
      },
      {
        "id": "DeathSquad",
        "name": "escuadrón de la muerte"
      }
    ]
  },
  {
    "id": "TSF",
    "name": "Federación Transolar",
    "description": "Sirve a los intereses de la Federación Transolar y obedece las órdenes del mando.",
    "color": "#22a7ff",
    "jobs": [
      {
        "id": "TSFMarine",
        "name": "Infante de marina de la Federación Transolar"
      }
    ]
  },
  {
    "id": "Administration",
    "name": "Administración de la instalación",
    "description": "El servicio administrativo dirige de forma general todas las áreas de actividad de la Fundación y a todos los niveles. Incluye todos los nodos de comunicaciones y centros de mando esenciales, cada uno de ellos redundante. También gestiona todos los recursos financieros de la Fundación: asignación de fondos, contabilidad, planificación presupuestaria y demás. Dada su especial importancia, el personal que trabaja aquí se somete con mayor frecuencia a controles de lealtad. Además de sus departamentos principales, el servicio administrativo cuenta con una división interna responsable de todo tipo de labores de oficina, gestión documental y archivo.",
    "color": "#065290",
    "jobs": [
      {
        "id": "Director",
        "name": "Director del complejo"
      },
      {
        "id": "ScientificServiceDirector",
        "name": "Director del servicio científico"
      },
      {
        "id": "SecurityCommander",
        "name": "Jefe de seguridad"
      },
      {
        "id": "ChiefTechnicalSpecialist",
        "name": "Ingeniero jefe"
      },
      {
        "id": "PersonnelOfficer",
        "name": "Responsable de personal"
      },
      {
        "id": "HeadOfMedicalSector",
        "name": "Director médico"
      },
      {
        "id": "SeniorLogisticsOfficer",
        "name": "Intendente"
      }
    ]
  },
  {
    "id": "MobileTaskForce",
    "name": "MTF",
    "description": "La naturaleza del trabajo de la Fundación SCP exige numerosos especialistas de perfiles muy concretos. Suele ser el caso de objetos SCP cuya contención requiere grandes esfuerzos y enfoques poco convencionales. Para estos y otros fines se forman las MTF. Son unidades pequeñas —por lo general, de diez a treinta miembros, aunque existen algunas mucho mayores— especializadas en tareas concretas o situaciones excepcionales. Cada fuerza recibe una combinación única de una letra griega y un número, que puede incluir prefijos aclaratorios.",
    "color": "#808080",
    "jobs": [
      {
        "id": "RRHLeader",
        "name": "{ mobile-task-force-rank-leader-name } { mobile-task-force-short-name } { mobile-task-force-RRH-name }"
      },
      {
        "id": "RRHSpecialist",
        "name": "{ mobile-task-force-rank-specialist-name } { mobile-task-force-short-name } { mobile-task-force-RRH-name }"
      },
      {
        "id": "HDLeader",
        "name": "{ mobile-task-force-rank-leader-name } { mobile-task-force-short-name } { mobile-task-force-HD-name }"
      },
      {
        "id": "HDSpecialist",
        "name": "{ mobile-task-force-rank-specialist-name } { mobile-task-force-short-name } { mobile-task-force-HD-name }"
      },
      {
        "id": "HDCadet",
        "name": "{ mobile-task-force-rank-cadet-name } { mobile-task-force-short-name } { mobile-task-force-HD-name }"
      },
      {
        "id": "MHLeader",
        "name": "{ mobile-task-force-rank-leader-name } { mobile-task-force-short-name } { mobile-task-force-MH-name }"
      },
      {
        "id": "MHSpecialist",
        "name": "{ mobile-task-force-rank-specialist-name } { mobile-task-force-short-name } { mobile-task-force-MH-name }"
      },
      {
        "id": "MHCadet",
        "name": "{ mobile-task-force-rank-cadet-name } { mobile-task-force-short-name } { mobile-task-force-MH-name }"
      },
      {
        "id": "LLHLeader",
        "name": "{ mobile-task-force-rank-leader-name } { mobile-task-force-short-name } { mobile-task-force-LLH-name }"
      },
      {
        "id": "LLHSpecialist",
        "name": "{ mobile-task-force-rank-specialist-name } { mobile-task-force-short-name } { mobile-task-force-LLH-name }"
      },
      {
        "id": "NTFLeader",
        "name": "{ mobile-task-force-rank-leader-name } { mobile-task-force-short-name } { mobile-task-force-NTF-name }"
      },
      {
        "id": "NTFSpecialist",
        "name": "{ mobile-task-force-rank-specialist-name } { mobile-task-force-short-name } { mobile-task-force-NTF-name }"
      },
      {
        "id": "NTFCadet",
        "name": "{ mobile-task-force-rank-cadet-name } { mobile-task-force-short-name } { mobile-task-force-NTF-name }"
      }
    ]
  },
  {
    "id": "FondSecurity",
    "name": "Servicio de Seguridad de la Fundación",
    "description": "La «policía exterior». Este departamento del servicio de seguridad depende directamente de la Administración Regional y se desplaza a distintas instalaciones de la Fundación para cumplir tareas concretas. Por lo general son agentes de seguridad corrientes, pero móviles.",
    "color": "#913030",
    "jobs": [
      {
        "id": "FondSecurityOfficer",
        "name": "oficial de seguridad de la Fundación"
      },
      {
        "id": "FondSeniorSecurityOfficer",
        "name": "oficial sénior de seguridad de la Fundación"
      }
    ]
  },
  {
    "id": "InternalSecurity",
    "name": "Departamento de Seguridad Interna",
    "description": "La espada castigadora de la Fundación: detecta amenazas entre el personal, ataja las infracciones de los protocolos y garantiza que la contención no se derrumbe por debilidad humana o traición.",
    "color": "#980000",
    "jobs": [
      {
        "id": "MentalControlOfficer",
        "name": "Oficial de control mental"
      },
      {
        "id": "InternalSecurityOperative",
        "name": "Agente de seguridad interna"
      }
    ]
  },
  {
    "id": "EthicsCommittee",
    "name": "Comité de Ética",
    "description": "El Comité de Ética decide qué es ético. Pese al enfoque utilitarista de la Fundación ante los dilemas morales, se asegura de que solo se hagan los sacrificios imprescindibles y de que siempre se elija la alternativa más ética. El personal de la Fundación debe recordar que el Comité de Ética observa, evalúa y dicta sentencia.",
    "color": "#741b47",
    "jobs": [
      {
        "id": "EthicsCommitteeRepresentative",
        "name": "Representante del Comité de Ética"
      }
    ]
  },
  {
    "id": "InternalTribunalService",
    "name": "Servicio de Tribunal Interno",
    "description": "El tribunal de última instancia de la Fundación, donde se juzga a los traidores, a quienes infringen los protocolos y a quienes han puesto en peligro la propia Contención. Sus sentencias no admiten recurso.",
    "color": "#c27ba0",
    "jobs": [
      {
        "id": "JudicialInspector",
        "name": "Inspector judicial"
      },
      {
        "id": "TribunalOfficer",
        "name": "Oficial del tribunal"
      }
    ]
  },
  {
    "id": "HeavyContainmentSecurityService",
    "name": "Unidad de Operaciones Especiales",
    "description": "Se encarga de custodiar los objetos y de hacerles frente cuando se produce una brecha de contención.",
    "color": "#770101",
    "jobs": [
      {
        "id": "HeavyContainmentZoneCommandant",
        "name": "Comandante de la UOE"
      },
      {
        "id": "SeniorHeavyContainmentZoneOfficer",
        "name": "Oficial sénior de la UOE"
      },
      {
        "id": "HeavyContainmentZoneOfficer",
        "name": "Oficial de la UOE"
      },
      {
        "id": "JuniorHeavyContainmentZoneOfficer",
        "name": "Oficial júnior de la UOE"
      }
    ]
  },
  {
    "id": "ExternalAdministrativeZoneSecurityService",
    "name": "Unidad de Seguridad de la Zona Administrativa Exterior",
    "description": "La «policía interior». Sus agentes mantienen el orden entre el personal de todas las instalaciones de la Fundación. También protegen los complejos residenciales y los almacenes que no intervienen en la contención de anomalías y garantizan la custodia segura del personal de clase D.",
    "color": "#999999",
    "jobs": [
      {
        "id": "ExternalAdministrativeZoneCommandant",
        "name": "Comandante jefe"
      },
      {
        "id": "SeniorExternalAdministrativeZoneOfficer",
        "name": "Comandante sénior"
      },
      {
        "id": "ExternalAdministrativeZoneOfficer",
        "name": "Comandante"
      },
      {
        "id": "JuniorExternalAdministrativeZoneOfficer",
        "name": "Comandante júnior"
      },
      {
        "id": "FieldMedicalSpecialist",
        "name": "Amnestesiólogo"
      }
    ]
  },
  {
    "id": "ScientificService",
    "name": "Servicio científico",
    "description": "El trabajo eficaz del servicio científico es la piedra angular de las actividades de la Fundación. Estudia todos los objetos SCP contenidos o recién recibidos, desarrolla medidas para contrarrestarlos y neutralizarlos en caso de brecha y crea equipos, dispositivos, medicamentos y mucho más para la propia Organización.",
    "color": "#43356d",
    "jobs": [
      {
        "id": "ScientificServiceDirector",
        "name": "Director del servicio científico"
      },
      {
        "id": "LeadResearcher",
        "name": "Investigador sénior"
      },
      {
        "id": "AnomarchologyResearcher",
        "name": "Investigador"
      },
      {
        "id": "ProductionSpecialist",
        "name": "Especialista en producción"
      },
      {
        "id": "JuniorResearcher",
        "name": "Auxiliar de laboratorio"
      }
    ]
  },
  {
    "id": "MedicalService",
    "name": "Servicio médico",
    "description": "El servicio médico mantiene en buen estado de salud a todo el personal de la Fundación. Por la naturaleza del trabajo de la Organización, sus sanitarios afrontan con frecuencia lesiones, traumatismos, infecciones y trastornos mentales especialmente difíciles e insólitos; por eso solo recluta a los mejores médicos. Tras cierto tiempo de servicio, algunos adquieren especialidades adicionales relacionadas directamente con determinados tipos de efectos, como los meméticos.",
    "color": "#3b627a",
    "jobs": [
      {
        "id": "HeadOfMedicalSector",
        "name": "Director médico"
      },
      {
        "id": "SeniorMedicalSpecialist",
        "name": "Médico sénior"
      },
      {
        "id": "PharmaceuticalSpecialist",
        "name": "Farmacéutico"
      },
      {
        "id": "MedicalSpecialist",
        "name": "Médico"
      },
      {
        "id": "Psychotherapist",
        "name": "Parapsicólogo"
      },
      {
        "id": "HospitalIntern",
        "name": "Auxiliar médico"
      }
    ]
  },
  {
    "id": "EngineeringTechnicalService",
    "name": "Servicio técnico y de ingeniería",
    "description": "El servicio técnico y de ingeniería se ocupa del mantenimiento técnico y general de todas las instalaciones y máquinas que utiliza la Fundación. Diseña y construye nuevas Zonas, Sectores, Sitios, otras estructuras y vías internas, y realiza toda clase de reparaciones y mantenimiento. Sus miembros se dividen en departamentos con distintos niveles de autorización y funciones; quienes poseen una autorización superior diseñan y construyen cámaras de contención para objetos de clase «Keter» y trabajan en otras estructuras estratégicas.",
    "color": "#c07d1e",
    "jobs": [
      {
        "id": "ChiefTechnicalSpecialist",
        "name": "Ingeniero jefe"
      },
      {
        "id": "LeadTechnicalSpecialist",
        "name": "Ingeniero sénior"
      },
      {
        "id": "GeneralTechnicalSpecialist",
        "name": "Técnico"
      },
      {
        "id": "ElectricalTechnicalSpecialist",
        "name": "Electrotécnico"
      },
      {
        "id": "TechnicalTrainee",
        "name": "Técnico en prácticas"
      }
    ]
  },
  {
    "id": "LogisticsService",
    "name": "Servicio de logística",
    "description": "El servicio de logística distribuye los recursos materiales, financieros y humanos entre las instalaciones de la Fundación. Los transportes se realizan por carretera, mar, ferrocarril, aire, espacio y otros medios. Un complejo sistema de prioridades y clases de importancia regula la asignación de recursos; por norma general, la máxima prioridad corresponde a los objetos SCP transportados, cualquiera que sea su clase, y a los recursos necesarios para contenerlos. Los obstáculos que impidan una entrega se eliminan con la máxima urgencia.",
    "color": "#9E6A34",
    "jobs": [
      {
        "id": "SeniorLogisticsOfficer",
        "name": "Intendente"
      },
      {
        "id": "LogisticsOfficer",
        "name": "Oficial de logística"
      }
    ]
  },
  {
    "id": "FoodAndSanitationServiceDepartment",
    "name": "Departamento de alimentación y saneamiento",
    "description": "Este departamento auxiliar de la Fundación SCP satisface las necesidades básicas de los empleados y mantiene un entorno cómodo para el personal. Agrupa tres equipos especializados: el equipo culinario, la sección de floricultura y el sector de higiene y saneamiento.",
    "color": "#4e7c22",
    "jobs": [
      {
        "id": "GastronomicSpecialist",
        "name": "Especialista gastronómico"
      },
      {
        "id": "BotanistPhytogeneticist",
        "name": "Botánico fitogenetista"
      },
      {
        "id": "ServicePersonnel",
        "name": "Personal de servicio"
      }
    ]
  },
  {
    "id": "LowAccessPersonnel",
    "name": "Personal de clase D",
    "description": "La clase D se asigna al personal prescindible empleado en trabajos con anomalías extremadamente peligrosas. Sus miembros suelen reclutarse entre presos de todos los países, con preferencia por los condenados por delitos violentos y, en especial, a muerte. Se los traslada a las instalaciones de la Fundación bajo una tapadera creíble. Deben someterse con regularidad a evaluaciones psiquiátricas obligatorias y, al final de cada mes, recibir un amnésico de clase B o superior o ser eliminados, a discreción del servicio de seguridad o del servicio médico local. Si se produce un incidente catastrófico en la instalación, todo el personal local de clase D deberá ser eliminado de inmediato salvo que el servicio de seguridad local decida lo contrario.",
    "color": "#91381e",
    "jobs": [
      {
        "id": "ClassDCook",
        "name": "Cocinero de clase D"
      },
      {
        "id": "ClassDBotanist",
        "name": "Botánico de clase D"
      },
      {
        "id": "ClassDJanitor",
        "name": "Limpiador de clase D"
      },
      {
        "id": "ClassD",
        "name": "Personal de clase D"
      }
    ]
  },
  {
    "id": "SCP",
    "name": "Objetos SCP",
    "description": "La encarnación viva —y no tan viva— de las pesadillas de la Fundación. Son la razón por la que los científicos encanecen, los guardias toman antidepresivos y existen todos esos protocolos. No se los puede destruir ni comprender: solo contener, hasta que descubran que no somos nosotros quienes escribimos las reglas.",
    "color": "#7a7070",
    "jobs": [
      {
        "id": "Scp049",
        "name": "SCP-049 «El Doctor de la Plaga»"
      },
      {
        "id": "Scp082",
        "name": "SCP-082 «Fernand el Caníbal»"
      },
      {
        "id": "Scp096",
        "name": "SCP-096 «El Chico Tímido»"
      },
      {
        "id": "Scp106",
        "name": "SCP-106 «El Viejo»"
      },
      {
        "id": "Scp173",
        "name": "SCP-173 «La Escultura»"
      },
      {
        "id": "Scp247",
        "name": "SCP-247 «El gatito inofensivo»"
      },
      {
        "id": "Scp457",
        "name": "SCP-457 «El Hombre Ardiente»"
      },
      {
        "id": "Scp939",
        "name": "SCP-939 «Con Muchas Voces»"
      },
      {
        "id": "Scp999",
        "name": "SCP-999 «El Monstruo de las Cosquillas»"
      }
    ]
  }
];
